import type { LearningLesson } from "../learn-data";
const z = (zh: string, en: string) => ({ zh, en });
// Open-book chapter checks are intentionally public; formal exam answers stay server-only.
type Check = [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];
const checks: Record<string, Check> = {
  "what-is-agent": [
    "每天定时读取天气并推送固定模板，需要先引入自主 Agent 吗？",
    "Does a scheduled weather lookup with a fixed template need an autonomous Agent?",
    "不一定，固定流程已能满足可预测任务。",
    "Not necessarily; a fixed workflow can satisfy the predictable task.",
    "需要，所有 API 调用都属于 Agent。",
    "Yes; every API call is an Agent.",
    "需要，否则程序无法定时执行。",
    "Yes; otherwise scheduling is impossible.",
    "自主性用于动态决策，不是固定任务的前提。",
    "Autonomy supports dynamic decisions, not basic scheduling.",
  ],
  "llm-basics": [
    "模型没有库存接口，却被问到实时库存，应该如何回答？",
    "A model has no inventory tool but is asked for live stock. What should it do?",
    "说明无法核对实时数据，并请求可靠来源。",
    "Explain that live data cannot be verified and request a reliable source.",
    "用训练知识给出确定库存。",
    "Report definite stock from training knowledge.",
    "把温度调成零后直接给出数字。",
    "Set temperature to zero and report a number.",
    "采样参数无法补充不存在的实时数据。",
    "Sampling settings cannot supply missing live data.",
  ],
  "prompt-contracts": [
    "模型返回可解析 JSON，但分类不在允许列表里，应如何处理？",
    "A model returns valid JSON with a disallowed category. What next?",
    "拒绝该结果或进入受控修复流程。",
    "Reject it or enter a controlled repair flow.",
    "JSON 合法，所以直接保存分类。",
    "Save it because the JSON is valid.",
    "让前端隐藏这个分类即可。",
    "Hide the category in the UI.",
    "语法校验和业务约束是两道不同的边界。",
    "Syntax and business constraints are separate validation boundaries.",
  ],
  "tool-schemas": [
    "订单工具收到其他用户的 ownerId，哪个检查不可省略？",
    "An order tool receives another user's ownerId. Which check is essential?",
    "使用已验证会话限制订单所有权。",
    "Scope order ownership to the verified session.",
    "只检查 ownerId 是否是字符串。",
    "Only check whether ownerId is a string.",
    "相信模型已经检查过身份。",
    "Trust that the model checked identity.",
    "参数类型正确不等于拥有资源访问权限。",
    "A valid parameter type does not grant resource access.",
  ],
  "state-and-memory": [
    "用户更改行程日期后，旧酒店报价如何处理？",
    "The user changes trip dates. What happens to old hotel quotes?",
    "标记失效，并按新日期重新查询。",
    "Invalidate them and fetch quotes for the new dates.",
    "只更新页面日期，继续使用旧报价。",
    "Update displayed dates but reuse old quotes.",
    "只要旧报价在聊天历史里就一直有效。",
    "Quotes remain valid while present in chat history.",
    "持久记录也需要版本与失效规则。",
    "Persistent records need versions and invalidation rules.",
  ],
  "agent-loop": [
    "Agent 已用尽步骤预算却没有完成任务，应该怎么做？",
    "An Agent exhausts its step budget without finishing. What next?",
    "停止并报告当前进展与未解决事项。",
    "Stop and report progress and unresolved items.",
    "忽略预算继续执行直到完成。",
    "Ignore the budget and run until done.",
    "清空日志后重新无限运行。",
    "Clear logs and restart without limits.",
    "预算是执行边界，失败也应是可解释的结果。",
    "Budgets bound execution; failure must also be explainable.",
  ],
  "multi-agent": [
    "两个工作者需要修改同一资源，如何降低冲突？",
    "Two workers need to edit the same resource. How can conflicts be reduced?",
    "指定写入所有者，并使用版本化交接。",
    "Assign a write owner and use versioned handoffs.",
    "让两者同时覆盖，最后写入者获胜。",
    "Let both overwrite; the last writer wins.",
    "不传来源，避免协调者看到差异。",
    "Omit sources so the coordinator cannot see differences.",
    "并行协作需要所有权、版本和合并规则。",
    "Parallel collaboration needs ownership, versions, and merge rules.",
  ],
  "agent-production": [
    "提示词更新后质量下降，生产系统应该具备什么能力？",
    "Quality drops after a prompt update. What capability should production provide?",
    "按版本定位失败，并回滚到已验证基线。",
    "Trace failures by version and roll back to a validated baseline.",
    "只保留最新提示词，不记录版本。",
    "Keep only the latest prompt without version records.",
    "通过隐藏错误提示解决质量问题。",
    "Hide error messages to fix quality.",
    "可观察与可回滚是生产交付的核心能力。",
    "Observability and rollback are core production capabilities.",
  ],
  "what-is-fullstack": [
    "点击保存后，何时应显示笔记已经持久化？",
    "After clicking Save, when should a note be shown as persisted?",
    "在服务端确认成功后，或明确标记为待同步。",
    "After server confirmation, or with an explicit pending-sync state.",
    "鼠标点击发生后立刻标记为数据库已保存。",
    "Mark it saved in the database immediately on click.",
    "页面上有文字就说明数据库已经写入。",
    "Visible text proves the database write succeeded.",
    "本地交互完成与持久化完成是不同状态。",
    "Local interaction completion differs from durable persistence.",
  ],
  "web-and-http": [
    "为什么不应该用 GET 接口删除笔记？",
    "Why should a GET endpoint not delete notes?",
    "GET 用于安全读取，预取和缓存可能重复触发它。",
    "GET is for safe reads and may be triggered by prefetching or caches.",
    "GET 请求不能包含 URL 参数。",
    "GET requests cannot include URL parameters.",
    "GET 永远不能返回 JSON。",
    "GET can never return JSON.",
    "读取请求不应造成删除等副作用。",
    "Read requests must not cause destructive side effects.",
  ],
  "semantic-html": [
    "执行保存操作应使用什么元素？",
    "Which element should perform a Save action?",
    "带有清晰名称的原生 button。",
    "A native button with a clear accessible name.",
    "没有键盘支持的可点击 div。",
    "A clickable div without keyboard support.",
    "没有目标地址的导航链接。",
    "A navigation link with no destination.",
    "原生按钮提供语义、焦点和键盘行为。",
    "Native buttons provide semantics, focus, and keyboard behavior.",
  ],
  "css-layout": [
    "窄屏出现横向溢出，应该优先做什么？",
    "A narrow layout overflows horizontally. What should you do first?",
    "检查长文本、图片和 Grid 子项的宽度约束。",
    "Inspect long text, images, and grid item width constraints.",
    "直接隐藏溢出，接受内容不可见。",
    "Hide overflow and accept invisible content.",
    "将所有元素设为固定桌面宽度。",
    "Give all elements fixed desktop widths.",
    "响应式应保持内容可见，而不只是遮住布局问题。",
    "Responsive design preserves content instead of masking layout errors.",
  ],
  "javascript-typescript": [
    "把网络响应断言为 Note 类型后，还需要校验吗？",
    "After casting a network response to Note, is validation still needed?",
    "需要，类型断言不会检查运行时数据。",
    "Yes; a type assertion does not validate runtime data.",
    "不需要，TypeScript 自动修改非法响应。",
    "No; TypeScript automatically repairs invalid responses.",
    "不需要，类型会随 JavaScript 传到服务端。",
    "No; types travel with JavaScript to the server.",
    "编译期类型不能替代外部输入的运行时检查。",
    "Compile-time types do not replace runtime checks of external input.",
  ],
  "async-errors": [
    "旧搜索请求后返回，如何避免覆盖新结果？",
    "An old search resolves late. How do you protect new results?",
    "取消旧请求或核对当前请求标识。",
    "Cancel obsolete requests or compare current request identifiers.",
    "按返回顺序全部写入当前列表。",
    "Apply every response in arrival order.",
    "删除加载提示，让用户看不到变化。",
    "Remove loading indicators to hide changes.",
    "网络响应顺序不一定等于用户请求顺序。",
    "Network response order need not match user request order.",
  ],
  "react-components": [
    "visibleNotes 可以由 notes 和 query 计算，应怎样管理？",
    "visibleNotes can be computed from notes and query. How should it be managed?",
    "在渲染时推导，避免重复保存同步状态。",
    "Derive it during rendering rather than storing duplicate state.",
    "额外保存一份，手动维护每次同步。",
    "Store a second copy and synchronize it manually.",
    "用随机数作为每个列表项的 key。",
    "Use random values as list keys.",
    "减少冗余状态能减少数据不一致的路径。",
    "Reducing redundant state reduces inconsistency paths.",
  ],
  "server-client": [
    "调用模型的秘密密钥应放在哪个边界？",
    "Where should a secret model API key live?",
    "服务端，并通过受保护的接口使用。",
    "On the server behind a protected endpoint.",
    "放在 NEXT_PUBLIC 环境变量中供浏览器读取。",
    "In a NEXT_PUBLIC variable available to the browser.",
    "隐藏在客户端组件的按钮样式里。",
    "Hidden in a client component's button styles.",
    "传给浏览器的数据无法作为秘密保护。",
    "Data delivered to the browser cannot remain secret.",
  ],
  "github-auth": [
    "GitHub 登录成功后，是否自动能读所有学习记录？",
    "Does GitHub sign-in automatically grant access to every learning record?",
    "不能，仍需逐次检查资源所有权。",
    "No; resource ownership still needs checking.",
    "可以，认证与授权是同一件事。",
    "Yes; authentication and authorization are identical.",
    "可以，只要隐藏其他用户的导航链接。",
    "Yes; just hide links to other users.",
    "身份验证不能替代每次数据访问的授权检查。",
    "Identity verification cannot replace authorization on data access.",
  ],
  "testing-security": [
    "删除按钮禁用能防止服务端重复删除请求吗？",
    "Does disabling Delete prevent repeated server-side delete requests?",
    "不能，服务端仍需验证权限和幂等行为。",
    "No; the server must enforce permissions and idempotent behavior.",
    "可以，浏览器是唯一能调用接口的地方。",
    "Yes; only the browser can call the endpoint.",
    "可以，只要按钮有灰色样式。",
    "Yes; a gray style is sufficient.",
    "界面保护不能替代可信服务端边界。",
    "UI safeguards cannot replace trusted server boundaries.",
  ],
  "product-introduction": [
    "访谈学习者时，哪类问题更适合先问？",
    "Which question should you ask a learner first?",
    "最近一次学习的过程、困难和期望结果。",
    "Their recent learning process, obstacles, and desired outcome.",
    "是否喜欢我已经决定要做的新功能。",
    "Whether they like the feature I already decided to build.",
    "哪个按钮颜色能证明产品成功。",
    "Which button color proves product success.",
    "观察任务证据比诱导式偏好问题更可靠。",
    "Task evidence is more reliable than leading preference questions.",
  ],
  "validate-and-scope": [
    "课程浏览量增加，能直接证明用户学会了吗？",
    "More lesson views appear. Does this prove learners mastered the material?",
    "不能，还需测验表现、完成行为与用户反馈。",
    "No; examine quiz performance, completion behavior, and feedback.",
    "可以，访问次数等于掌握程度。",
    "Yes; visits equal mastery.",
    "可以，不需要检查退出和失败用户。",
    "Yes; dropouts and failures need no investigation.",
    "流量、完成和掌握是不同层次的指标。",
    "Traffic, completion, and mastery are different measures.",
  ],
};
export function topicCheckpoint(
  slug: string,
): LearningLesson["challenge"] | undefined {
  const row = checks[slug];
  if (!row) return undefined;
  const [
    question,
    enQuestion,
    answer,
    enAnswer,
    wrong,
    enWrong,
    wrong2,
    enWrong2,
    reason,
    enReason,
  ] = row;
  // Rotate public options per topic so correctness is not tied to one position.
  const options = [
    {
      label: z(answer, enAnswer),
      feedback: z(reason, enReason),
      correct: true,
    },
    { label: z(wrong, enWrong), feedback: z(reason, enReason), correct: false },
    {
      label: z(wrong2, enWrong2),
      feedback: z(reason, enReason),
      correct: false,
    },
  ];
  const offset = slug.length % options.length;
  return {
    question: z(question, enQuestion),
    options: [...options.slice(offset), ...options.slice(0, offset)],
  };
}
