import type { LearningLesson } from "../learn-data";
import type { LearningGuide } from "../learn-guides";
import { topicCheckpoint } from "./checkpoints";

const z = (zh: string, en: string) => ({ zh, en });
type Topic = [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];
// slug, title (zh/en), explanation (zh/en), worked example (zh/en), task (zh/en), code, misconception (zh/en).
const topics: Record<string, Topic[]> = {
  agent: [
    [
      "what-is-agent",
      "从零认识 Agent",
      "What is an Agent?",
      "Agent 是围绕目标观察环境并执行动作的系统。LLM 负责理解和选择，工具负责访问外部世界，程序负责限制权限与执行次数。先区分固定流程与自主决策：能用明确规则完成的任务，不一定需要 Agent。",
      "An Agent observes its environment and takes actions toward a goal. An LLM interprets and selects; tools access external systems; application code limits permissions and execution. Distinguish a fixed workflow from autonomous decisions: predictable tasks may not need an Agent.",
      "以查天气为例：输入城市，查询天气接口，返回结果是固定流程；为了安排周末行程，系统需要比较天气与交通，再决定查询什么，才体现基于观察的行动选择。",
      "Fetching weather for a city is a fixed workflow. Planning a weekend requires comparing weather and transport and deciding what to investigate next: actions depend on observations.",
      "列出三个日常任务，分别标记为规则程序、固定 LLM 流程或 Agent，并写出不使用 Agent 的理由。",
      "Classify three everyday tasks as rule-based software, fixed LLM workflows, or Agents, and explain when you would avoid an Agent.",
      "const task = { goal: 'plan a weekend', maxSteps: 5, tools: ['weather', 'transit'] };",
      "不要把所有使用 LLM 的程序都称为 Agent。增加自主性也会增加成本、失败路径和权限风险，应先找到确实需要动态决策的部分。",
      "Not every LLM application is an Agent. More autonomy creates costs, failure paths, and permission risks; identify where dynamic decisions are genuinely useful.",
    ],
    [
      "llm-basics",
      "理解 LLM 的能力与边界",
      "LLM capabilities and limits",
      "LLM 根据上下文预测输出，不是事实数据库。上下文窗口限制可见信息，采样使相同请求可能得到不同结果，知识截止与外部状态变化使回答需要验证。把事实交给检索，把执行交给工具，把验收交给程序。",
      "LLMs predict outputs from context rather than acting as factual databases. Context windows limit visibility, sampling creates variation, and changing external state requires verification. Retrieve facts, execute through tools, and validate with code.",
      "同一个模型分别回答已提供文档中的价格和今天的库存。前者可以引用输入，后者如果没有库存接口只能承认未知；自信的语言并不能证明数据实时。",
      "Ask a model for a price in a supplied document and today's stock level. The first can cite input; the second requires an inventory tool. Confident language is not evidence of live data.",
      "用同一问题测试三次，记录差异；再加入事实材料，检查答案是否明确区分已知、推断与未知。",
      "Repeat a question three times, record differences, then supply evidence and check that the answer separates facts, inferences, and unknowns.",
      "const input = { question: 'Current inventory?', evidence: [], allowGuessing: false };",
      "不要用温度为零代替事实校验，也不要假设模型一定记得上一轮。每轮所需状态必须显式进入上下文，敏感信息要先脱敏。",
      "Zero temperature is not fact checking, and conversational memory is not guaranteed. Supply required state explicitly and redact sensitive information.",
    ],
    [
      "prompt-contracts",
      "提示词与结构化输出",
      "Prompts and structured output",
      "提示词应说明任务、输入边界、输出结构和失败条件。结构化输出让下游程序能读取结果，但语法正确不代表内容正确；仍需验证字段范围、引用来源和业务约束。把不可信文档放在数据区，而不是当作指令。",
      "Specify the task, input boundaries, output schema, and failure conditions. Structured output makes responses machine-readable but valid syntax does not ensure correct content. Validate ranges, sources, and business rules; treat untrusted documents as data rather than instructions.",
      "工单分类返回 category、confidence 和 reason。程序只接受三种分类；低置信度进入人工队列，不允许模型直接新增分类或决定是否删除工单。",
      "A ticket classifier returns category, confidence, and reason. Accept only allowed categories; route uncertain cases to humans rather than allowing the model to invent categories or delete tickets.",
      "设计工单分类的输出类型，并写出空输入、非法分类和低置信度三个测试案例。",
      "Define a ticket classification schema and test empty input, invalid categories, and low confidence.",
      "type Classification = { category: 'bug' | 'question' | 'request'; confidence: number; reason: string };",
      "不要仅凭 JSON 可解析就执行后续动作。模型输出与用户输入一样需要服务端验证，错误应该有可解释的恢复路径。",
      "Do not execute actions just because JSON parses. Validate model output like user input and provide an explicit recovery path.",
    ],
    [
      "tool-schemas",
      "工具接口与参数校验",
      "Tool schemas and validation",
      "工具是模型和业务系统之间的窄接口。每个工具只做一件事，明确参数、返回结果、超时与副作用。模型提出调用建议，程序验证权限与参数后才执行；工具描述必须解释何时使用以及何时不能使用。",
      "Tools are narrow interfaces between models and business systems. Each should have one responsibility, explicit parameters, results, timeouts, and side effects. Models propose calls; application code validates permissions and arguments before execution.",
      "搜索订单工具只允许读取当前用户的订单。即使模型传入其他用户的 ID，服务端也应使用登录身份约束查询，而不是相信模型提供的 owner 字段。",
      "An order search tool only reads the current user's orders. Enforce ownership using authenticated identity even if the model supplies another user's ID.",
      "为一个只读搜索工具写出输入、输出和错误类型，并测试越权、缺参、空结果与超时。",
      "Define a read-only search tool's inputs, outputs, and errors; test unauthorized access, missing fields, empty results, and timeouts.",
      "type SearchInput = { query: string; limit: number };\nconst validLimit = (n: number) => Number.isInteger(n) && n > 0 && n <= 20;",
      "工具能被模型调用不代表模型拥有执行权限。不要把 API 密钥放进提示词，也不要向模型暴露不必要的敏感返回字段。",
      "Tool availability does not grant execution permission. Keep API keys out of prompts and minimize sensitive result fields.",
    ],
    [
      "state-and-memory",
      "状态、上下文与记忆",
      "State, context, and memory",
      "状态记录任务当前位置；上下文是本轮模型能看到的材料；记忆是跨轮保留的信息。三者不能混用。把结构化事实存入状态，按需构造上下文，并为长期记忆设置来源、更新时间和删除规则。",
      "State records task position, context is what a model sees this turn, and memory persists across turns. Store facts structurally, assemble context deliberately, and give long-term memory provenance, timestamps, and deletion rules.",
      "旅行规划状态保留预算和日期，当前上下文仅放入相关酒店。用户改动日期后，应使旧报价失效，而不是继续引用历史对话里的价格。",
      "A trip planner stores budget and dates in state and selects relevant hotels for context. Changing dates invalidates old quotes rather than silently reusing conversational prices.",
      "画出一个任务状态表，列出可持久化字段、临时字段和更新后必须失效的字段。",
      "Design a task state table separating persistent and temporary fields, and identify fields invalidated by updates.",
      "type State = { taskId: string; dates: string[]; quoteVersion: number; status: 'running' | 'waiting' | 'done' };",
      "不要无限追加聊天记录作为记忆。上下文会变贵且冲突增多，应保留可追溯事实并明确失效规则，避免跨用户泄露。",
      "Do not use an endlessly growing chat log as memory. Preserve traceable facts with invalidation rules and isolate each user's data.",
    ],
    [
      "agent-loop",
      "构建有限行动循环",
      "Build a bounded action loop",
      "行动循环包括观察、决策、执行和更新。为每轮设置步骤预算、时间预算与停止条件；工具失败应产生可识别结果，不能让模型无上限重试。等待确认是合法状态，不应被当作失败强行继续。",
      "An action loop observes, decides, executes, and updates. Bound steps and time, define stop conditions, and encode tool failures explicitly. Waiting for confirmation is a valid state, not a failure to bypass.",
      "研究助手最多查询五次，找到两份独立来源后结束。网络失败只重试一次；需要付费下载时进入等待状态，让用户决定是否继续。",
      "A research assistant searches at most five times and stops after finding two independent sources. Retry a network failure once; wait for permission before a paid download.",
      "实现一个最多执行三次的模拟循环，分别测试成功、预算耗尽与等待确认。",
      "Build a three-step simulated loop and test success, budget exhaustion, and waiting for confirmation.",
      "for (let step = 0; step < 3; step++) {\n  const observation = await runReadOnlyStep(step);\n  if (observation.done || observation.needsApproval) break;\n}",
      "不要把每次工具失败都变成继续调用模型的理由。重复尝试应受预算控制，并记录最后可恢复的状态和失败原因。",
      "A failed tool is not a reason for unlimited model calls. Bound retries and record the last recoverable state with the failure reason.",
    ],
    [
      "multi-agent",
      "多 Agent 协作与交接",
      "Multi-Agent collaboration",
      "多 Agent 适合可分离、能独立验收的子任务。协调者定义输入、产物与合并规则，工作者只处理自己的职责。共享状态要有所有权与版本；并行写入同一资源容易产生冲突。先证明单 Agent 的不足，再增加协作。",
      "Use multiple Agents for separable tasks with independently verifiable outputs. A coordinator defines inputs, deliverables, and merge rules. Give shared state ownership and versions; prove why a single Agent is insufficient before adding coordination.",
      "资料收集和代码审查可以并行，最终报告由协调者合并。两个 Agent 不应同时修改同一数据库记录，交接时必须注明来源和未解决的问题。",
      "Research and code review can run in parallel before a coordinator merges results. Avoid simultaneous edits to the same record and include sources and unresolved issues in handoffs.",
      "把一个研究任务拆成两项独立工作，写出交接协议、冲突规则和统一验收标准。",
      "Split a research task into two independent jobs and specify handoff contracts, conflict rules, and acceptance criteria.",
      "type Handoff = { taskId: string; version: number; findings: string[]; sources: string[]; unresolved: string[] };",
      "更多 Agent 不一定更准确。协作会增加延迟、上下文和合并成本，应先测量收益，并避免没有验收标准的相互讨论。",
      "More Agents do not guarantee accuracy. Measure added latency, context, and merging costs; avoid discussion without acceptance criteria.",
    ],
    [
      "agent-production",
      "把 Agent 带到生产环境",
      "Operate Agents in production",
      "上线前先定义可度量的任务成功率、错误率、费用与延迟。记录每次模型与工具调用的关联 ID，但不要记录密钥和完整个人数据。采用小流量发布、可回滚版本和人工接管，模型版本变化也需要回归评测。",
      "Define measurable task success, errors, cost, and latency before launch. Correlate model and tool calls without logging secrets or unnecessary personal data. Use staged rollouts, rollback versions, human takeover, and regression tests for model changes.",
      "客服助手先对少量只读问题开放；错误分类上升时回滚提示词版本。真正退款仍要求明确授权，且使用幂等键防止重复执行。",
      "Release a support assistant to a small read-only cohort first and roll back prompt versions when classifications regress. Refunds require authorization and idempotency keys.",
      "提交一份上线检查单，包含评测样本、预算、告警、回滚和人工接管条件。",
      "Write a launch checklist with evaluation samples, budgets, alerts, rollback, and human takeover conditions.",
      "const run = { traceId: crypto.randomUUID(), promptVersion: 'v1', maxCost: 0.10, mode: 'read-only' };",
      "演示成功不等于生产可靠。不要用单次正确回答作为上线依据；必须观察失败样本、权限边界和版本变更后的回归结果。",
      "A successful demo is not production reliability. Evaluate failures, permission boundaries, and regressions after version changes.",
    ],
  ],
  fullstack: [
    [
      "what-is-fullstack",
      "从零认识全栈开发",
      "What is full-stack development?",
      "全栈应用由浏览器界面、服务端逻辑、数据存储和部署环境共同组成。浏览器负责呈现与交互，服务端负责可信业务规则，数据库保存持久状态。理解一次请求经过哪些边界，比先选择框架更重要。",
      "A full-stack application combines a browser interface, server logic, persistent storage, and deployment. Browsers present interactions, servers enforce trusted rules, and databases persist state. Understand request boundaries before choosing frameworks.",
      "保存笔记时，浏览器发送内容，服务端检查身份和长度，数据库写入记录，再返回 ID。页面显示成功应基于响应，而不是只因为按钮被点击。",
      "Saving a note sends content from the browser, validates identity and length on the server, writes a database row, and returns an ID. Show success from the response, not merely from a click.",
      "画出保存笔记的完整请求链路，并标明每一步发生在浏览器、服务端还是数据库。",
      "Draw a note-saving request flow and label which steps run in the browser, server, or database.",
      "type Note = { id: string; ownerId: string; body: string; createdAt: string };",
      "全栈不是把所有逻辑都放在一个页面。前端校验改善体验，服务端校验保护数据，两者职责不同，不能互相代替。",
      "Full stack does not mean putting all logic on one page. Client validation improves UX; server validation protects data. They cannot replace each other.",
    ],
    [
      "web-and-http",
      "浏览器、URL 与 HTTP",
      "Browsers, URLs, and HTTP",
      "URL 标识资源，HTTP 请求用方法、头与正文表达操作，响应通过状态码、头与正文返回结果。GET 应用于读取；写入操作要考虑身份、重复提交和缓存。HTTPS 加密传输，但不替你实现访问控制。",
      "URLs identify resources. HTTP methods, headers, and bodies express requests; status codes, headers, and bodies return results. Use GET for reads, consider identity and duplicate submissions for writes, and remember HTTPS does not implement access control.",
      "打开开发者工具观察笔记接口：200 表示读取成功，401 表示未登录，403 表示无权限，404 表示资源不可见。不要让每种失败都显示同一个网络错误。",
      "Inspect a notes endpoint: 200 indicates success, 401 missing authentication, 403 denied permission, and 404 an unavailable resource. Do not present every failure as an identical network error.",
      "记录一次页面请求的方法、地址、状态码和响应类型，为四种失败写出用户提示。",
      "Inspect a request's method, URL, status, and response type, then write user-facing messages for four failure cases.",
      "const response = await fetch('/api/notes');\nif (!response.ok) throw new Error(`HTTP ${response.status}`);",
      "不要把 HTTPS 当作权限校验，也不要用 GET 执行删除。浏览器缓存与预取可能重复读取请求，副作用应使用合适的方法。",
      "HTTPS is not authorization; do not delete through GET. Caching and prefetching may repeat reads, so use suitable methods for side effects.",
    ],
    [
      "semantic-html",
      "语义化 HTML 与可访问性",
      "Semantic HTML and accessibility",
      "HTML 描述内容结构，语义元素让浏览器和辅助技术理解页面。链接用于导航，按钮用于操作；表单字段需要标签，错误需要明确关联。键盘焦点、标题层级和图片替代文本都是基本功能，不是上线后的装饰。",
      "HTML describes structure for browsers and assistive technology. Links navigate, buttons perform actions, inputs need labels, and errors need explicit associations. Keyboard focus, heading hierarchy, and alternative text are basic functionality.",
      "登录表单使用 label 与 input，提交按钮有明确文本，错误区使用状态提示。只用鼠标测试看不到焦点丢失，应该用 Tab 完成整次提交。",
      "A login form uses associated labels, a clearly named submit button, and announced errors. Test the entire submission with Tab; mouse-only testing misses focus failures.",
      "做一个可用键盘提交的笔记表单，检查标签、焦点、错误提示和标题层级。",
      "Build a keyboard-operable notes form and check labels, focus, errors, and heading hierarchy.",
      '<label htmlFor="body">Note</label>\n<textarea id="body" name="body" required />\n<button type="submit">Save</button>',
      "不要用可点击的 div 代替按钮。加上鼠标事件并不能自动提供键盘操作、焦点样式和辅助技术所需的语义。",
      "A clickable div is not a button. Mouse events do not provide keyboard behavior, focus, or assistive semantics automatically.",
    ],
    [
      "css-layout",
      "CSS 布局与响应式",
      "CSS layout and responsive design",
      "布局先处理内容宽度、间距和阅读顺序，再加入视觉效果。Flex 适合一维排列，Grid 适合二维区域。用流式宽度与必要的断点适应屏幕，避免固定高度裁切内容；动效应尊重减少动态效果的偏好。",
      "Design content width, spacing, and reading order before effects. Flex handles one-dimensional layout; Grid handles two-dimensional regions. Use fluid widths and purposeful breakpoints, avoid clipping fixed heights, and respect reduced motion.",
      "笔记列表在窄屏为单列，宽屏出现阅读侧栏。侧栏应按内容需要出现，而不是为了某个设备型号；正文行宽限制能提高阅读舒适度。",
      "A notes list uses one column on narrow screens and gains a reading sidebar when space permits. Choose breakpoints from content needs and constrain text width for readability.",
      "制作从 320px 到桌面都不横向溢出的两栏页面，并用长标题和空列表测试。",
      "Build a two-column layout that avoids horizontal overflow from 320px to desktop; test long headings and empty lists.",
      ".layout { display: grid; gap: 2rem; }\n@media (min-width: 60rem) { .layout { grid-template-columns: 16rem minmax(0, 1fr); } }",
      "不要通过隐藏溢出掩盖布局错误。检查长文本、图片尺寸与 Grid 子项最小宽度，保证内容仍然可读且键盘可操作。",
      "Do not hide overflow to mask layout problems. Check long text, image sizes, and minimum grid item widths while preserving readability and keyboard access.",
    ],
    [
      "javascript-typescript",
      "JavaScript 与 TypeScript 基础",
      "JavaScript and TypeScript foundations",
      "JavaScript 控制运行时行为，TypeScript 在开发阶段检查类型。理解函数、对象、数组与不可变更新，再使用类型表达输入输出。外部数据不会因为类型断言变得安全，仍需要运行时验证。",
      "JavaScript controls runtime behavior; TypeScript checks types during development. Learn functions, objects, arrays, and immutable updates, then type inputs and outputs. Type assertions do not make external data safe; validate it at runtime.",
      "从接口获得的标题可能不是字符串。直接断言为 Note 会隐藏问题；使用 typeof 和长度约束后再进入渲染，才能给出可靠错误提示。",
      "An API title may not be a string. Casting to Note hides the problem; validate type and length before rendering to provide reliable errors.",
      "写一个接收 unknown 的标题校验函数，测试数字、空字符串、超长输入和正常输入。",
      "Write a title validator accepting unknown and test numbers, empty strings, oversized inputs, and valid strings.",
      "function isTitle(value: unknown): value is string {\n  return typeof value === 'string' && value.trim().length > 0 && value.length <= 120;\n}",
      "不要滥用 any 或类型断言跳过检查。类型在编译后消失，网络响应、表单和环境变量仍是必须验证的边界。",
      "Avoid any and unchecked assertions. Types disappear after compilation; network responses, forms, and environment variables still need validation.",
    ],
    [
      "async-errors",
      "异步请求与错误恢复",
      "Async requests and recovery",
      "异步任务存在等待、成功、失败与取消。请求可能乱序返回，离开页面后可能继续运行。用 AbortController 取消无用请求，检查 HTTP 状态，并区分可重试的网络失败与不可重试的权限或参数错误。",
      "Async work can wait, succeed, fail, or be canceled. Responses may arrive out of order or after navigation. Cancel obsolete requests with AbortController, inspect HTTP status, and distinguish retryable network failures from permission or validation errors.",
      "搜索框连续输入会发出多次查询。旧请求如果后返回可能覆盖新结果；取消旧请求或核对请求 ID，才能保证屏幕对应当前输入。",
      "Typing in search sends multiple queries. A late old response can overwrite newer results; cancel earlier requests or verify request IDs before updating the screen.",
      "实现可取消搜索，模拟慢响应与断网，确保旧结果不会覆盖当前搜索条件。",
      "Implement cancelable search and simulate slow responses and offline states; ensure stale results cannot replace current results.",
      "const controller = new AbortController();\nfetch('/api/search', { signal: controller.signal });\n// Cancel obsolete work:\ncontroller.abort();",
      "不要对所有失败无限重试。写请求可能重复产生副作用，重试前要检查幂等性、预算和用户是否仍需要这次操作。",
      "Do not retry every failure indefinitely. Writes can duplicate effects; check idempotency, budgets, and whether the operation is still needed.",
    ],
    [
      "react-components",
      "React 组件与数据流",
      "React components and data flow",
      "组件把界面拆成可复用的职责，props 传递输入，state 保存随交互变化的数据。渲染应该根据当前状态计算结果，避免同时保存可以推导出的重复状态。列表使用稳定 ID 作为 key，不使用随位置变化的序号。",
      "Components separate UI responsibilities, props carry input, and state stores changing interaction data. Derive results from current state rather than storing redundant values. Use stable IDs as list keys rather than positional indexes.",
      "笔记列表保存 notes 与 query，通过过滤计算 visibleNotes。若另外保存 visibleNotes，就需要维护两份数据同步，删除或搜索时更容易出现不一致。",
      "Store notes and query, then derive visibleNotes through filtering. Storing the filtered list separately creates synchronization problems during deletion or search.",
      "把笔记界面拆为列表、搜索和编辑器，标明每个状态的拥有者和数据流方向。",
      "Split a notes UI into list, search, and editor components; identify state owners and data-flow direction.",
      "const visibleNotes = notes.filter(note => note.title.includes(query));\nreturn visibleNotes.map(note => <NoteCard key={note.id} note={note} />);",
      "不要通过 Effect 同步所有可计算数据。优先在渲染时推导，只有与外部系统同步时才考虑 Effect 并正确清理。",
      "Do not synchronize every derived value through Effects. Derive values during rendering; use Effects for external synchronization with proper cleanup.",
    ],
    [
      "server-client",
      "服务端与客户端边界",
      "Server and client boundaries",
      "Next.js 服务端组件适合读取数据与保护密钥，客户端组件处理状态和浏览器交互。use client 定义客户端模块边界，不意味着整个应用都应该搬到浏览器。服务器到客户端的参数需要可序列化，秘密数据永远不应传过去。",
      "Next.js Server Components suit data access and secret protection; Client Components handle browser interactions and state. use client defines a module boundary, not a reason to move the entire app to the browser. Pass serializable props and never transmit secrets.",
      "课程正文在服务端渲染，测验选择按钮使用客户端组件。模型密钥留在服务器接口，浏览器只发送经过校验的问题，不能直接读取环境密钥。",
      "Render lesson text on the server and use a client component for quiz selections. Keep model keys in server endpoints; browsers submit validated questions without reading secrets.",
      "标记一个课程页的组件边界，解释正文、进度按钮、密钥和数据库查询应放在哪里。",
      "Map a lesson page's component boundaries and locate prose, progress controls, secrets, and database queries.",
      "// Server component\nexport default async function Page() {\n  const lessons = await readLessons();\n  return <LessonList lessons={lessons} />;\n}",
      "不要给包含密钥的变量添加 NEXT_PUBLIC 前缀。客户端打包的数据可以被访客读取，隐藏按钮也不能保护服务端权限。",
      "Never mark secrets NEXT_PUBLIC. Visitors can inspect client bundles, and hiding a button does not enforce server authorization.",
    ],
    [
      "github-auth",
      "GitHub 登录与权限",
      "GitHub sign-in and authorization",
      "OAuth 让第三方确认身份，但应用仍需建立自己的会话与权限规则。登录回调要验证状态并限制跳转目标；数据库查询必须按当前用户过滤。认证回答你是谁，授权回答你可以做什么，两者缺一不可。",
      "OAuth delegates identity verification but your application still owns sessions and permissions. Validate callback state, constrain redirects, and scope database queries to the current user. Authentication identifies users; authorization controls allowed actions.",
      "GitHub 登录后，用户只能读取自己的学习记录。即使在请求正文传入别人的 userId，接口也应从服务端会话取得真实身份并拒绝越权。",
      "After GitHub sign-in, users read only their own learning records. Ignore a submitted foreign userId and derive identity from the server session.",
      "画出 GitHub 登录到进度同步的流程，列出未登录、回调失败和越权查询的预期结果。",
      "Map GitHub sign-in through progress synchronization and define outcomes for missing sessions, callback failures, and unauthorized queries.",
      "const user = await requireSession(request);\nconst notes = await database.notes.findMany({ ownerId: user.id });",
      "不要将用户提交的 ID 当作身份，也不要将服务端管理密钥放到前端。跨站写请求、会话过期和回调白名单都需要单独处理。",
      "Submitted IDs are not identity. Keep service keys server-side and handle cross-site writes, session expiry, and callback allowlists deliberately.",
    ],
    [
      "testing-security",
      "测试、安全与性能",
      "Testing, security, and performance",
      "测试分层覆盖纯函数、接口与关键用户旅程。优先验证失败路径、权限隔离和重复提交，而不仅是页面能打开。性能从测量开始，区分慢数据库、过大资源与客户端计算，再针对瓶颈优化。",
      "Test pure functions, API boundaries, and critical user journeys. Cover failures, ownership isolation, and duplicate submissions, not just page loading. Measure performance to distinguish slow databases, oversized assets, and client computation before optimizing.",
      "保存笔记的测试既包含正常提交，也包含无身份、超长内容和同一请求重发。部署后观察接口耗时分布，不能只看一次本地请求很快。",
      "Test note saves with valid input, missing identity, oversized content, and repeated requests. Observe deployed latency distributions rather than one fast local request.",
      "为笔记应用列出六个自动化测试，并记录一个性能基线与可回滚的优化方案。",
      "Define six automated tests for a notes app and record a performance baseline with a reversible optimization plan.",
      "const cases = ['valid', 'unauthenticated', 'forbidden', 'invalid', 'duplicate', 'timeout'];",
      "测试通过不代表没有漏洞。避免在日志记录令牌与私人内容，并持续检查依赖、授权边界和上线后的真实失败。",
      "Passing tests do not prove security. Keep tokens and private content out of logs and monitor dependencies, authorization boundaries, and real failures.",
    ],
  ],
  product: [
    [
      "product-introduction",
      "产品实战从哪里开始",
      "Where product practice begins",
      "产品不是功能的集合，而是帮助特定用户在特定情境下完成任务。先观察现有工作方式与困难，再定义改进目标。把想法、事实和假设分开，避免用个人偏好代替用户证据。",
      "A product helps specific people accomplish tasks in a context rather than merely collecting features. Observe existing workflows and difficulties before defining improvements. Separate ideas, facts, and assumptions instead of treating preferences as evidence.",
      "学习平台的目标不是增加页面数量，而是让初学者知道先学什么、何时练习以及如何检验理解。课程顺序与考试反馈应围绕这个目标设计。",
      "A learning platform should help beginners know what to study first, when to practice, and how to check understanding. Sequence lessons and feedback around that goal, not page counts.",
      "访谈或观察一位潜在学习者，记录当前任务、困难和成功标准，避免直接询问喜欢哪些功能。",
      "Interview or observe a potential learner and record tasks, obstacles, and success criteria rather than asking which features they like.",
      "const hypothesis = { user: 'beginner', task: 'learn systematically', evidenceNeeded: 'can choose the next lesson' };",
      "不要把所有反馈立刻变成功能。先确认是否属于目标用户和核心任务，再判断修改是否能被验证且不会增加额外理解成本。",
      "Do not turn every comment into a feature. Check target users and core tasks, then validate that a change helps without adding unnecessary cognitive cost.",
    ],
    [
      "validate-and-scope",
      "验证假设与控制范围",
      "Validate assumptions and scope",
      "MVP 应验证最危险的假设，不是把完整产品每部分都做一点。为假设定义可观察行为与停止条件，限定首版范围，并明确哪些指标不能说明成功。实验结束后根据证据决定继续、修改或停止。",
      "An MVP tests risky assumptions rather than building a little of everything. Define observable behavior and stop conditions, limit scope, and identify misleading metrics. Decide whether to continue, revise, or stop from evidence.",
      "先发布一条可完成的课程路径，观察用户是否完成第一课并理解反馈。浏览量无法证明学会了；需要结合测验表现、退出位置和访谈。",
      "Release one complete learning path and observe first-lesson completion and feedback understanding. Views do not prove learning; combine quiz performance, exit points, and interviews.",
      "为一个课程 MVP 写出假设、测量方式、时间范围和继续或停止的标准。",
      "Specify a course MVP's hypothesis, measurement method, time window, and continue-or-stop criteria.",
      "const experiment = { hypothesis: 'clear sequence improves completion', primaryMetric: 'firstLessonCompleted', windowDays: 14 };",
      "不要在看到一次积极反馈后扩张所有功能。先检查样本、失败用户和替代解释，并为实验设置范围与复盘时间。",
      "Do not expand every feature after one positive response. Examine sampling, unsuccessful users, and alternative explanations within a bounded review period.",
    ],
  ],
};

export const EXTRA_LESSONS: Record<string, LearningLesson[]> = {};
export const EXTRA_GUIDES: Record<string, LearningGuide> = {};
for (const [track, rows] of Object.entries(topics)) {
  EXTRA_LESSONS[track] = rows.map(
    ([
      slug,
      title,
      englishTitle,
      explanation,
      englishExplanation,
      example,
      englishExample,
      task,
      englishTask,
      code,
      pitfall,
      englishPitfall,
    ]) => {
      const takeaway = z(explanation, englishExplanation);
      EXTRA_GUIDES[`${track}/${slug}`] = {
        scenario: z(example, englishExample),
        steps: [
          { title: z("分析边界", "Identify boundaries"), detail: takeaway },
          {
            title: z("观察具体过程", "Inspect the concrete flow"),
            detail: z(example, englishExample),
          },
          {
            title: z("验证失败路径", "Validate failure paths"),
            detail: z(pitfall, englishPitfall),
          },
        ],
        task: z(task, englishTask),
        checks: [
          z(
            "提交可阅读的实现或流程图，并注明输入和输出。",
            "Submit readable code or a diagram with explicit inputs and outputs.",
          ),
          z(
            "至少覆盖一个成功案例与一个失败案例。",
            "Cover at least one successful case and one failure case.",
          ),
          z(
            "解释本课的边界，写出仍未解决的一项限制。",
            "Explain the boundaries and document one remaining limitation.",
          ),
        ],
        pitfall: z(pitfall, englishPitfall),
      };
      const challenge = topicCheckpoint(slug);
      if (!challenge) throw new Error(`Missing checkpoint for ${slug}`);
      return {
        slug,
        number: "",
        title: z(title, englishTitle),
        summary: z(task, englishTask),
        minutes: 25,
        concept: [
          takeaway,
          z(example, englishExample),
          z(pitfall, englishPitfall),
        ],
        model: [
          { label: z("理解", "Understand"), detail: takeaway },
          { label: z("应用", "Apply"), detail: z(example, englishExample) },
          { label: z("验证", "Verify"), detail: z(task, englishTask) },
        ],
        code,
        challenge,
      };
    },
  );
}

export const COURSE_ORDER: Record<string, string[]> = {
  agent: [
    "what-is-agent",
    "llm-basics",
    "agent-vs-chat",
    "prompt-contracts",
    "tool-schemas",
    "state-and-memory",
    "agent-loop",
    "rag-pipeline",
    "tools-and-confirmation",
    "multi-agent",
    "evaluation-and-recovery",
    "agent-production",
  ],
  fullstack: [
    "what-is-fullstack",
    "web-and-http",
    "semantic-html",
    "css-layout",
    "javascript-typescript",
    "async-errors",
    "react-components",
    "interface-state",
    "server-client",
    "api-contracts",
    "data-models",
    "github-auth",
    "testing-security",
    "production-delivery",
  ],
  product: [
    "product-introduction",
    "define-the-problem",
    "validate-and-scope",
    "map-the-workflow",
    "design-the-surface",
    "ship-and-observe",
  ],
};
export const STAGE_TITLES = [
  z("认识与入门", "Introduction"),
  z("基础与练习", "Foundations"),
  z("构建与实战", "Build and practice"),
  z("深入与交付", "Advanced delivery"),
];
export function lessonStage(index: number, total: number) {
  return Math.min(3, Math.floor((index * 4) / total));
}
