"use client";
import {useState} from "react";
import {useLanguage} from "@/components/site/language-provider";
import {SchoolNav} from "./school-nav";
import {SchoolAccount} from "./school-account";
import {LEARNING_TRACKS,lessonKey} from "@/lib/learn-data";
import {schoolError} from "@/lib/school-error";
import {TransitionLink} from "@/components/site/transition-link";
export function AiSchool(){
 const {locale}=useLanguage(),zh=locale==="zh";const lessons=LEARNING_TRACKS.flatMap(t=>t.lessons.map(l=>({key:lessonKey(t.slug,l.slug),title:l.title})));
 const [mode,setMode]=useState("tutor"),[lesson,setLesson]=useState(lessons[0].key),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [result,setResult]=useState<{text:string;latency:number;tokens:number;source:string}>();
 return <main className="mx-auto max-w-5xl px-5 py-20"><TransitionLink href="/learn">← FIELD SCHOOL</TransitionLink><SchoolNav/><h1 className="font-display text-5xl">{zh?"边提问，边理解。":"Ask. Experiment. Understand."}</h1><p className="mt-5 text-muted">{zh?"课程导师依据选定课程提供学习提示；模型练习场用于比较自己的提问方式。每次都是独立对话，不会自动发送历史。":"The tutor uses the selected lesson; the playground helps you experiment with prompts. Each request is independent; conversation history is not sent."}</p><SchoolAccount/><form className="rounded-3xl border border-line bg-panel p-6" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");setResult(undefined);try{const r=await fetch("/api/school/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,lesson,prompt,locale})});const b=await r.json();if(!r.ok)throw Error(b.error);setResult(b);}catch(e){setError(e instanceof Error?schoolError(e.message,locale):(zh?"连接失败":"Connection failed"));}finally{setBusy(false);}}}>
 <div className="grid gap-5 sm:grid-cols-2"><label>{zh?"模式":"Mode"}<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper p-3"><option value="tutor">{zh?"课程导师":"Course tutor"}</option><option value="playground">{zh?"模型练习场":"LLM playground"}</option></select></label><label>{zh?"参考课程":"Reference lesson"}<select value={lesson} onChange={e=>setLesson(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper p-3">{lessons.map(l=><option value={l.key} key={l.key}>{l.title[locale]}</option>)}</select></label></div>
 <label className="mt-6 block">{zh?"你的问题":"Your prompt"}<textarea required maxLength={3000} rows={7} value={prompt} onChange={e=>setPrompt(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper p-4"/></label><p className="my-4 text-xs text-muted">{zh?"问题及选定课程摘要会发送至 OpenAI。请勿输入密钥或个人敏感信息。每账户每天最多 10 次，全站每天最多 200 次；失败请求也计入额度。AI 可能出错，请核对课程。":"Your prompt and selected lesson context are sent to OpenAI. Do not enter secrets or sensitive information. Limit: 10 requests per account/day, 200 site-wide/day, including failures. AI can be wrong; check the lesson."}</p><button disabled={busy||!prompt.trim()} className="rounded-full bg-ink px-6 py-3 text-paper disabled:opacity-40">{busy?(zh?"正在生成…":"Generating…"):(zh?"发送问题":"Send prompt")}</button></form>
 {error&&<p role="alert" className="mt-6">{error}</p>}{result&&<section aria-live="polite" className="mt-8 rounded-3xl border border-line p-6"><p className="whitespace-pre-wrap leading-8">{result.text}</p><p className="mt-6 text-xs text-muted">{result.latency} ms · {result.tokens??"—"} tokens</p><TransitionLink className="mt-4 inline-block text-accent" href={result.source}>{zh?"查看参考课程（并非逐句引文）":"View reference lesson (not sentence-level citations)"} ↗</TransitionLink></section>}</main>;
}
