"use client";
import {useEffect,useState} from "react";
import {useLanguage} from "@/components/site/language-provider";
import {localProgress} from "./use-learning-progress";
import {LEARNING_TRACKS,lessonKey} from "@/lib/learn-data";
type Records={userId:string;submissions:{track:string;repository:string;reflection:string}[];profile:null|{display_name:string;bio:string;is_public:boolean};attestations:{id:string;lesson_key:string}[]};
export function CloudWorkspace(){
 const {locale}=useLanguage(),zh=locale==="zh";
 const [data,setData]=useState<Records>(),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [track,setTrack]=useState("agent"),[repository,setRepository]=useState(""),[reflection,setReflection]=useState("");
 const [name,setName]=useState(""),[bio,setBio]=useState(""),[isPublic,setPublic]=useState(false);
 const [lesson,setLesson]=useState(0),[answer,setAnswer]=useState(-1);
 const lessons=LEARNING_TRACKS.flatMap(t=>t.lessons.map(l=>({key:lessonKey(t.slug,l.slug),...l})));
 async function load(){const r=await fetch("/api/school/records");if(r.ok){const d:Records=await r.json();setData(d);setName(d.profile?.display_name||"");setBio(d.profile?.bio||"");setPublic(d.profile?.is_public||false);}}
 useEffect(()=>{void load().catch(()=>setNotice(zh?"云端记录读取失败":"Could not load cloud records"));},[zh]);
 async function save(body:unknown){setBusy(true);setNotice("");try{const r=await fetch("/api/school/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);await load();window.dispatchEvent(new Event("nextfield-learning-progress"));setNotice(zh?"已保存到云端。":"Saved to the cloud.");}catch(e){setNotice(e instanceof Error?e.message:"Error");}finally{setBusy(false);}}
 const input="mt-2 w-full rounded-xl border border-line bg-paper p-3";
 if(!data)return <p className="mt-8 text-sm text-muted">{notice|| (zh?"登录并配置云端后，可提交项目和管理公开档案。":"Sign in when cloud services are configured to submit projects and manage your profile.")}</p>;
 return <div className="mt-12 space-y-8">
 <p role="status" className="text-accent">{notice}</p>
 <section className="rounded-3xl border border-line p-6"><h2 className="text-2xl">{zh?"导入本机记录":"Import browser progress"}</h2><p className="my-4 text-sm text-muted">{zh?"不会自动合并访客记录。导入仅记录自报进度，不会生成服务器检查题凭证。":"Guest progress is never merged automatically. Import is self-reported progress, not a checkpoint attestation."}</p><button disabled={busy} className="underline" onClick={()=>save({kind:"progress",keys:localProgress()})}>{zh?"导入到当前账户":"Import into this account"}</button></section>
 <div className="grid gap-8 lg:grid-cols-2"><form onSubmit={e=>{e.preventDefault();void save({kind:"submission",track,repository,reflection});}} className="rounded-3xl border border-line p-6"><h2 className="mb-5 text-2xl">{zh?"项目作业":"Project submission"}</h2><label>{zh?"课程路径":"Learning path"}<select className={input} value={track} onChange={e=>{setTrack(e.target.value);const s=data.submissions.find(s=>s.track===e.target.value);setRepository(s?.repository||"");setReflection(s?.reflection||"");}}>{LEARNING_TRACKS.map(t=><option value={t.slug} key={t.slug}>{t.title[locale]}</option>)}</select></label><p className="my-3 text-sm text-muted">{LEARNING_TRACKS.find(t=>t.slug===track)?.outcome[locale]}</p><label>GitHub {zh?"仓库":"repository"}<input className={input} required type="url" value={repository} onChange={e=>setRepository(e.target.value)}/></label><label>{zh?"实现、取舍与测试复盘（50–6000 字）":"Implementation, trade-offs and tests (50–6000 characters)"}<textarea className={input} required minLength={50} maxLength={6000} rows={5} value={reflection} onChange={e=>setReflection(e.target.value)}/></label><button disabled={busy} className="mt-4 rounded-full bg-ink px-5 py-3 text-paper">{zh?"保存项目（仅自己可见）":"Save project (private)"}</button><p className="mt-4 text-sm text-muted">{zh?"保存不代表已审核；此版本不读取仓库或自动评分。":"Saving does not imply review. This version does not inspect repositories or auto-grade."}</p>{data.submissions.map(s=><p key={s.track} className="mt-3 text-sm"><a href={s.repository} target="_blank" rel="noreferrer" className="underline">{s.track} ↗</a> <button type="button" onClick={()=>{setTrack(s.track);setRepository(s.repository);setReflection(s.reflection);}}>{zh?"编辑":"Edit"}</button></p>)}</form>
 <form onSubmit={e=>{e.preventDefault();void save({kind:"profile",name,bio,isPublic});}} className="rounded-3xl border border-line p-6"><h2 className="mb-5 text-2xl">{zh?"学习档案":"Learning profile"}</h2><label>{zh?"公开名称":"Display name"}<input className={input} required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>{zh?"介绍":"Bio"}<textarea className={input} rows={4} maxLength={300} value={bio} onChange={e=>setBio(e.target.value)}/></label><label className="mt-5 flex gap-3"><input type="checkbox" checked={isPublic} onChange={e=>setPublic(e.target.checked)}/>{zh?"公开名称、介绍和检查题记录":"Publish name, bio and checkpoint records"}</label><p className="my-4 text-sm text-muted">{zh?"默认私密；关闭并保存后，公开档案与验证链接均不可访问。作业与复盘始终不公开。":"Private by default. Disable and save to hide profile and verification links. Projects and reflections stay private."}</p><button disabled={busy} className="rounded-full bg-ink px-5 py-3 text-paper">{zh?"保存档案":"Save profile"}</button>{data.profile?.is_public&&<a className="ml-4 underline" href={`/learn/people/${data.userId}`}>{zh?"查看公开页":"Public profile"} ↗</a>}</form></div>
 <section className="rounded-3xl border border-line p-6"><h2 className="text-2xl">{zh?"服务器检查题记录":"Server checkpoint records"}</h2><p className="my-4 text-sm text-muted">{zh?"仅证明账户提交了正确选项，不是身份验证、监考考试或职业资格认证。":"Records that an account submitted a correct answer; not identity verification, a proctored exam or professional certification."}</p><select aria-label={zh?"选择检查题":"Choose checkpoint"} className={input} value={lesson} onChange={e=>{setLesson(Number(e.target.value));setAnswer(-1);}}>{lessons.map((l,i)=><option key={l.key} value={i}>{l.title[locale]}</option>)}</select><p className="my-5">{lessons[lesson].challenge.question[locale]}</p>{lessons[lesson].challenge.options.map((o,i)=><label key={i} className="my-3 flex gap-3"><input type="radio" name="checkpoint" checked={answer===i} onChange={()=>setAnswer(i)}/>{o.label[locale]}</label>)}<button disabled={busy||answer<0} className="mt-4 underline" onClick={()=>save({kind:"checkpoint",key:lessons[lesson].key,answer})}>{zh?"提交服务器验证":"Submit for server verification"}</button>{data.attestations.map(a=><p className="mt-3 text-sm" key={a.id}>{lessons.find(l=>l.key===a.lesson_key)?.title[locale]} · {data.profile?.is_public?<a className="underline" href={`/learn/verify/${a.id}`}>{zh?"验证链接":"Verification link"}</a>:zh?"公开档案后可分享":"Publish profile to share"}</p>)}</section>
 </div>;
}
