"use client";
import {useEffect,useRef,useState} from "react";
import {useLanguage} from "@/components/site/language-provider";
import {SchoolNav} from "./school-nav";
import {TransitionLink} from "@/components/site/transition-link";
import {SCHOOL_EXERCISES,exerciseDocument} from "@/lib/school-exercises";
export function CodePractice(){
 const {locale}=useLanguage(),zh=locale==="zh";
 const [index,setIndex]=useState(0),[code,setCode]=useState(SCHOOL_EXERCISES[0].starter),[busy,setBusy]=useState(false),[doc,setDoc]=useState(""),[error,setError]=useState("");
 const [results,setResults]=useState<{pass:boolean;actual:string}[]>([]);
 const frame=useRef<HTMLIFrameElement>(null),nonce=useRef(""),timer=useRef<ReturnType<typeof setTimeout>>();
 const exercise=SCHOOL_EXERCISES[index];
 useEffect(()=>{try{const saved=localStorage.getItem("school-code-"+exercise.id);setCode(saved?.slice(0,10000)||exercise.starter);}catch{setCode(exercise.starter);}setResults([]);setError("");setDoc("");setBusy(false);nonce.current="";clearTimeout(timer.current);},[exercise]);
 useEffect(()=>{function receive(e:MessageEvent){if(e.source!==frame.current?.contentWindow||e.data?.type!=="school-exercise"||e.data.nonce!==nonce.current)return;clearTimeout(timer.current);setBusy(false);setDoc("");const result=e.data.result;if(Array.isArray(result))setResults(result.slice(0,20).map(r=>({pass:r?.pass===true,actual:String(r?.actual).slice(0,200)})));else setError(String(result?.error||"Execution failed"));}window.addEventListener("message",receive);return()=>{window.removeEventListener("message",receive);clearTimeout(timer.current);};},[]);
 function run(){setBusy(true);setError("");setResults([]);nonce.current=crypto.randomUUID();try{localStorage.setItem("school-code-"+exercise.id,code);}catch{/* Draft storage is optional. */}setDoc(exerciseDocument(code,exercise.fn,exercise.tests,nonce.current));timer.current=setTimeout(()=>{setBusy(false);setDoc("");setError(zh?"沙箱超时或不可用，请重试。":"Sandbox timed out or is unavailable. Please retry.");},3000);}
 return <main className="mx-auto max-w-6xl px-5 py-20"><TransitionLink href="/learn">← FIELD SCHOOL</TransitionLink><SchoolNav/><h1 className="font-display text-5xl">{zh?"把理解写成代码。":"Turn understanding into code."}</h1><p className="my-6 text-muted">{zh?"无需登录，代码只在浏览器隔离环境中执行；不上传、不访问网络。练习结果不是云端认证。":"No login required. Code runs in an isolated browser environment without uploads or network access. Practice results are not cloud certification."}</p>
 <div className="grid gap-8 lg:grid-cols-[16rem_1fr]"><aside className="space-y-3">{SCHOOL_EXERCISES.map((x,i)=><button key={x.id} disabled={busy} aria-pressed={index===i} onClick={()=>{try{localStorage.setItem("school-code-"+exercise.id,code);}catch{}setIndex(i);}} className={`w-full rounded-xl border p-4 text-left ${index===i?"border-accent bg-panel":"border-line"}`}>{String(i+1).padStart(2,"0")} / {x.title[locale]}</button>)}</aside><section><h2 className="text-2xl">{exercise.title[locale]}</h2><p className="my-5 leading-7 text-muted">{exercise.description[locale]}</p><label className="text-sm" htmlFor="school-code">JavaScript</label><textarea id="school-code" spellCheck={false} maxLength={10000} value={code} onChange={e=>setCode(e.target.value)} rows={13} className="mt-2 w-full rounded-2xl border border-line bg-ink p-5 font-mono text-sm text-paper" /><div className="mt-4 flex gap-5"><button onClick={run} disabled={busy} className="rounded-full bg-ink px-6 py-3 text-paper">{busy?(zh?"运行中…":"Running…"):(zh?"运行测试":"Run tests")}</button><button disabled={busy} onClick={()=>{if(confirm(zh?"恢复初始代码？当前草稿将被替换。":"Restore starter code? This replaces your draft.")){setCode(exercise.starter);try{localStorage.removeItem("school-code-"+exercise.id);}catch{}}}}>{zh?"重置代码":"Reset code"}</button></div><div role="status" className="mt-6">{error&&<p>{zh?"执行未完成：":"Execution incomplete: "}{error}</p>}{results.map((r,i)=><p className="my-2 break-all font-mono text-sm" key={i}>{r.pass?"✓":"×"} {zh?"测试":"Test"} {i+1} · {zh?"返回":"Returned"} {r.actual} · {zh?"预期":"Expected"} {String(exercise.tests[i]?.expected)}</p>)}</div><details className="mt-6"><summary>{zh?"查看测试用例":"View test cases"}</summary><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(exercise.tests,null,2)}</pre></details></section></div>
 {doc&&<iframe ref={frame} title={zh?"代码执行沙箱":"Code execution sandbox"} sandbox="allow-scripts" srcDoc={doc} className="hidden"/>}</main>;
}
