"use client";

import { ArrowUpRight, CheckCircle2, GraduationCap } from "lucide-react";
import { TransitionLink } from "@/components/site/transition-link";
import { useLanguage } from "@/components/site/language-provider";
import { LEARNING_TRACKS, lessonKey } from "@/lib/learn-data";
import { useLearningProgress } from "@/components/learn/use-learning-progress";

export function FieldSchoolCallout() {
  const { locale } = useLanguage();
  const { completed } = useLearningProgress();
  return <section className="mx-auto max-w-site px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="overflow-hidden rounded-[2rem] bg-ink text-paper"><div className="grid lg:grid-cols-[1.1fr_.9fr]"><div className="p-7 sm:p-10 lg:p-14"><div className="flex items-center gap-3 font-mono text-[10px] tracking-[0.18em] text-liquid-foam"><GraduationCap className="size-4" />{locale === "zh" ? "核心功能 / FIELD SCHOOL" : "MAIN EXPERIENCE / FIELD SCHOOL"}</div><h2 className="mt-10 max-w-3xl font-display text-[clamp(3.5rem,7vw,6.5rem)] leading-[0.84] tracking-[-0.065em]">{locale === "zh" ? "学习 AGENT，" : "LEARN AGENTS."}<br /><span className="text-paper/45">{locale === "zh" ? "构建真实产品。" : "BUILD PRODUCTS."}</span></h2><p className="mt-7 max-w-xl text-sm leading-7 text-paper/60">{locale === "zh" ? "通过 12 节交互课程，把 Agent、全栈开发与产品设计连接起来。每节课都有心智模型、代码骨架和检查点。" : "Connect Agent development, full-stack engineering and product design through 12 interactive lessons, each with a mental model, code skeleton and checkpoint."}</p><TransitionLink className="mt-9 inline-flex items-center gap-3 rounded-full bg-liquid-foam px-5 py-3 text-sm text-ink hover:bg-paper" href="/learn">{locale === "zh" ? "进入 FIELD SCHOOL" : "Enter FIELD SCHOOL"}<ArrowUpRight className="size-4" /></TransitionLink></div><div className="border-t border-paper/10 p-5 lg:border-l lg:border-t-0 lg:p-7">{LEARNING_TRACKS.map((track) => { const count = track.lessons.filter((lesson) => completed.includes(lessonKey(track.slug, lesson.slug))).length; return <TransitionLink className="group flex min-h-40 flex-col rounded-2xl border border-paper/10 p-5 hover:border-liquid-foam/60 hover:bg-paper/[0.04]" href={`/learn/${track.slug}`} key={track.slug}><div className="flex items-center justify-between"><span className="font-mono text-[9px] tracking-[0.15em] text-liquid-foam">{locale === "zh" ? "路径" : "PATH"} / {track.number}</span><span className="flex items-center gap-1.5 font-mono text-[9px] text-paper/40">{count === track.lessons.length ? <CheckCircle2 className="size-3 text-liquid-foam" /> : null}{count}/{track.lessons.length}</span></div><div className="mt-auto flex items-end justify-between gap-4"><div><h3 className="font-display text-2xl">{track.shortTitle[locale]}</h3><p className="mt-2 text-xs leading-5 text-paper/45">{track.summary[locale]}</p></div><ArrowUpRight className="size-4 shrink-0 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div></TransitionLink>; })}</div></div></div></section>;
}
