export const EN_TRANSLATIONS: Record<string, string> = {
  "访问统计": "Analytics", "统计": "Analytics", "公开查看 Cloudflare 汇总访问、缓存与带宽趋势。": "Explore aggregate Cloudflare traffic, cache, and bandwidth trends.",
  "这里记录正在发生的事：做过的项目、持续的学习，以及下一步想去的方向。": "A record of what's in motion: projects built, lessons learned, and directions still unfolding.",
  "首页": "Index", "关于我": "About", "项目": "Projects", "写作": "Notes", "实验室": "Lab", "建站纪事": "Build Log", "制作说明": "Colophon", "失败博物馆": "Failure Museum",
  "把 AI 能力，变成真正好用的产品。": "Turn AI capabilities into products people can actually use.",
  "看看我做过的项目": "Explore selected work", "阅读制作说明": "Read the colophon", "进入完整实验室": "Enter the full lab", "查看全部笔记": "View all notes", "查看项目档案": "Open project archive",
  "首页不承担个人介绍，而是一张会持续生长的地图：新的内容可以从任何一个节点进入。": "The homepage is not a biography. It is a growing map where every node can become an entrance.",
  "项目、笔记与实验会在这里不断增加，也可以随时重新编排。": "Projects, notes and experiments keep arriving here, ready to be rearranged at any time.",
  "从作品、笔记或实验进入，同一个实践的不同切面。": "Enter through work, notes or experiments: different views of the same practice.",
  "Agent 工作台、运行观测与语义检索，记录从问题到产品的过程。": "Agent workspaces, operations and semantic retrieval—from problem to product.",
  "仍在生长的观点、技术取舍、过程记录与可以被复用的方法。": "Ideas in progress, technical trade-offs, process notes and reusable methods.",
  "触碰文字、空间与信号，把尚未命名的想法做成可以操作的原型。": "Touch type, space and signals; turn unnamed ideas into working prototypes.",
  "项目不是孤立的卡片，而是一组共享技术、方法与问题意识的节点。": "Projects are not isolated cards, but connected nodes sharing technology, methods and questions.",
  "知识检索、引用与工具调用的统一入口。": "One interface for retrieval, citations and tool use.",
  "观察、调试和评估复杂 Agent 流程。": "Observe, debug and evaluate complex Agent workflows.",
  "连接业务数据与用户真实意图。": "Connect business data with real user intent.",
  "这个持续生长的数字场域本身。": "The continuously growing digital field itself.",
  "日期是随机种子：同一天生成同一张封面，明天它会自然改变。": "The date is the seed: everyone sees the same cover today, and a new form tomorrow.",
  "项目需要完整证据，笔记允许仍在生长，实验只回答一个小问题。": "Projects need complete evidence, notes may keep growing, and experiments answer one small question.",
  "把复杂能力做成产品": "Turn complex capabilities into products", "记录仍在形成的判断": "Record judgments still taking shape", "用实验回答小问题": "Answer small questions through experiments", "查看此刻正在发生什么": "See what is happening right now",
  "Agent 工作台、运行观测与语义检索。": "Agent workspaces, observability and semantic retrieval.", "技术取舍、设计方法与过程复盘。": "Technical trade-offs, design methods and process reviews.", "粒子、空间、声音与界面反馈。": "Particles, space, sound and interface feedback.", "当前方向、构建记录和下一步计划。": "Current direction, build history and what comes next.",
  "进入频道": "Enter channel", "可以被触碰的小型研究：文字、空间与界面反馈如何产生感觉。": "Small studies you can touch: how type, space and feedback create feeling.",
  "移动指针扰动文字，点击让粒子重新集合。": "Move the pointer to disturb the type; click to gather it again.", "移动指针，观察平面如何产生空间层次。": "Move the pointer and watch a flat surface develop depth.",
  "点击能力节点，查看它如何落到项目、文章、实验和真实取舍中。": "Select a capability to see how it appears in projects, notes, experiments and real trade-offs.",
  "从问题、约束和成功指标开始，而不是从功能清单开始。": "Start from the problem, constraints and success criteria—not a feature list.",
  "工作流、工具调用、状态管理与可恢复任务。": "Workflows, tool use, state management and recoverable tasks.", "把输出质量、运行轨迹和失败路径变成可观察信号。": "Turn output quality, traces and failure paths into observable signals.",
  "让等待、确认、错误与结果拥有清晰的界面状态。": "Give waiting, confirmation, failure and results clear interface states.", "以类型、性能、可访问性和静态部署约束完成交付。": "Deliver within type, performance, accessibility and static-hosting constraints.", "用克制的 transform 与反馈建立空间感，而不是堆叠特效。": "Create spatial feeling with restrained transforms and feedback, not stacked effects.",
  "查看证据 01": "View evidence 01", "查看证据 02": "View evidence 02",
  "不等想法彻底完成才发布；先留下可被继续推演的版本。": "Do not wait for ideas to become final; publish a version that can keep evolving.",
  "为什么把作品集做成一个持续生长的索引": "Why turn a portfolio into a living index", "不使用重型场景，如何给网页增加空间感": "How to add depth without a heavy 3D scene", "Agent 界面首先是一台状态机": "An Agent interface is a state machine first",
  "与其等待一个永远不会真正完成的作品集，不如先建立一个能够持续容纳项目、笔记与实验的场域。": "Instead of waiting for a portfolio to feel finished, build a field that can continuously hold projects, notes and experiments.",
  "用克制的透视、Z 轴分层和指针反馈建立深度，同时为触屏和减少动态效果模式保留安静的版本。": "Use restrained perspective, depth layers and pointer feedback while preserving a quiet version for touch and reduced motion.",
  "聊天框只是入口；真正决定体验的，是等待、调用工具、请求确认、失败与恢复这些状态如何被呈现。": "The chat box is only an entrance; the experience depends on how waiting, tools, confirmation, failure and recovery are presented.",
  "你此刻处于什么状态？": "What state are you in right now?", "选择一个颜色": "Choose a color", "留下匿名信号": "Leave an anonymous signal", "信号已留下": "Signal received", "痕迹只保存在你的浏览器中，不上传身份或行为数据。": "This trace stays in your browser. No identity or behavior data is uploaded.",
  "十三个模块把能力声明变成可以浏览、操作、下载或被程序读取的证据。": "Thirteen modules turn capability claims into evidence you can browse, operate, download or read programmatically.",
  "关闭叙事噪音，只看职责、证据、结果与链接。": "Remove narrative noise and inspect responsibilities, evidence, outcomes and links.", "在真实约束下作出 Agent 产品决定并查看后果。": "Make Agent product decisions under real constraints and inspect the consequences.", "逐层拆开产品界面、状态、工作流与数据。": "Take apart the interface, state, workflow and data layer by layer.", "供程序和未来 Agent 读取的公开静态 JSON。": "Public static JSON for programs and future Agents.", "可下载、适合转发的一页式能力与项目 PDF。": "A downloadable one-page PDF of capabilities and selected work.",
  "按月份回看网站内容、封面和方向的变化。": "Review changes in content, covers and direction month by month.", "查看一个交互组件从静态版本到可访问 3D 的演变。": "See an interaction evolve from a static surface to accessible 3D.", "公开构建体积、静态页面与体验预算。": "Publish build size, static output and the experience budget.", "通过探索任务认识整个站点并生成 Field Pass。": "Explore the site through missions and generate a Field Pass.", "围绕每月问题留下结构化、匿名、本地优先的观点。": "Leave structured, anonymous, local-first responses to a monthly question.", "把项目、笔记、声音和工作室放入可拖动窗口。": "Place projects, notes, sound and the studio in draggable windows.", "把项目、笔记与日志生成可下载 PNG 卡片。": "Turn projects, notes and logs into downloadable PNG cards.",
  "检查对比度、键盘焦点、动态偏好与静态降级。": "Inspect contrast, keyboard focus, motion preferences and static fallbacks.", "无障碍不是发布前的检查项，而是颜色、焦点、动态和降级路径在设计阶段共同形成的系统。": "Accessibility is not a pre-release checkbox; it is shaped by color, focus, motion and fallback decisions from the start.",
  "输入命令或页面名称…": "Type a command or page…", "90 秒了解我": "90-second brief", "打开 Field Radio": "Open Field Radio", "关闭": "Close", "上一页": "Previous", "下一页": "Next", "打开联系方式": "Open contact",
  "一个持续生长的项目、笔记与实验索引。关注 Agent 产品、界面状态与现代全栈实现。": "A living index of projects, notes and experiments focused on Agent products, interface states and modern full-stack delivery.",
  "把工具调用、长任务、确认、错误和恢复设计成用户能够理解并控制的产品体验。": "Design tools, long tasks, confirmations, failures and recovery as an experience people can understand and control.",
  "覆盖 Agent 架构、语义检索、运行观测、前端交互与生产交付，而不是只完成一层演示界面。": "Cover Agent architecture, semantic retrieval, observability, interaction and production delivery—not just a demo surface.",
  "通过小型实验验证交互，用 Build Log 记录变化，用 Failure Museum 保留错误判断。": "Validate interactions through small experiments, record changes in the Build Log and preserve wrong turns in the Failure Museum.",
  "适合讨论 Agent 产品、AI 应用、界面系统或需要从原型走向完整交付的合作。": "Open to Agent products, AI applications, interface systems and collaborations that need to move from prototype to delivery.",
  "Field Agent 正在等待接入。": "Field Agent is waiting to be connected.", "数字分身的界面和入口已经保留。未来将基于本站项目、笔记与 Build Log 回答问题，并提供可追溯的内容引用；当前版本不会模拟模型回答。": "The interface and entry point are reserved. A future version will answer from site projects, notes and build logs with traceable citations; this version does not simulate model responses.",
  "下载 Field Pack": "Download Field Pack", "开始回放": "Start replay", "向下探索": "Explore downward", "探索方向": "Explore directions", "联系我": "Contact me", "联系": "Contact", "访问 GitHub": "Visit GitHub",
  "选择一个方案。这里不会只告诉你对错，而会展开用户体验、安全风险和工程前提。": "Choose an approach. The lab explains UX consequences, safety risks and engineering assumptions rather than only marking right or wrong.",
  "回到首页": "Return home", "回到白天": "Return to daylight", "继续实验": "Continue experimenting",
  "把想法，": "Turn ideas", "做成产品。": "into products.", "以下为可直接替换链接、描述和技术标签的作品占位内容。": "Selected work showing links, context and technical decisions.",
  "面向团队知识库的 Agent 工作台，将文档检索、引用与工具调用整合到一次自然对话中。": "An Agent workspace for team knowledge that brings retrieval, citations and tool use into one natural conversation.",
  "用于观察、调试与评估 Agent 运行情况的内部平台，帮助团队持续优化复杂流程。": "An internal platform for observing, debugging and evaluating Agent runs so teams can improve complex workflows.",
  "将结构化业务数据与语义检索结合，为产品提供更贴近意图的搜索体验。": "Combines structured business data with semantic retrieval for search that better reflects user intent.",
  "写下来的东西。": "Things written down.", "把踩过的坑与验证过的方法整理成可复用的文字。": "Turn hard-won lessons and tested methods into reusable writing.", "查看全部文章": "View all writing", "全部": "All", "全部文章": "All writing", "回到全部文章": "Back to all writing",
  "Agent 开发": "Agent development", "让模型推理、工具调用与知识检索在产品中可靠发生。": "Make model reasoning, tool use and knowledge retrieval work reliably inside products.", "框架支撑": "Framework support",
  "把目标、约束与上下文表达得更准确。": "Express goals, constraints and context precisely.", "将非结构化信息转为可计算的语义。": "Turn unstructured information into computable meaning.", "向量数据库": "Vector database", "设计高效的检索、索引与召回策略。": "Design efficient retrieval, indexing and recall strategies.", "让模型从可信的私有知识中回答。": "Ground model answers in trusted private knowledge.", "LLM 调用": "LLM calls", "可靠地连接模型、工具与业务上下文。": "Reliably connect models, tools and business context.", "多 Agent 编排": "Multi-Agent orchestration", "让角色、任务与工具协同完成复杂流程。": "Coordinate roles, tasks and tools across complex workflows.", "流式输出": "Streaming output", "降低等待感，让反馈在生成时发生。": "Reduce perceived wait time by returning feedback as it is generated.", "构建可控、可观测的 Agent 工作流。": "Build controllable and observable Agent workflows.", "为 AI 体验提供流式交互界面。": "Create streaming interfaces for AI experiences.",
  "两个 Hero 抢着开场": "Two heroes competing for the opening", "连续使用两块满屏巨幅标题，希望加强叙事力度。": "Used two consecutive full-screen statements to intensify the story.", "两个区域承担了相同任务，访问者需要穿过两次序言才能抵达内容。": "Both sections did the same job, forcing visitors through two introductions before reaching the content.", "保留第一屏作为宣言，把第二屏改造成可更新的 Now 状态。": "Kept the first screen as the manifesto and turned the second into an updateable Now state.",
  "让每一张卡片都动起来": "Making every card move", "为所有内容同时加入悬浮、扫光、位移和旋转。": "Added hover, shine, movement and rotation to every piece of content at once.", "反馈失去优先级，页面持续要求注意力，低性能设备也会更吃力。": "Feedback lost its hierarchy, the page demanded constant attention and slower devices suffered.", "只让关键入口拥有空间反馈，滚动动效使用一次性入场。": "Reserved spatial feedback for key entrances and used one-time scroll reveals.",
  "把聊天框当作 Agent 产品": "Treating a chat box as the Agent product", "先完成对话界面，再考虑工具调用过程如何呈现。": "Built the conversation UI before considering how tool execution should appear.", "用户看不到任务状态，也无法判断何时需要介入或如何恢复。": "Users could not see task state, know when to intervene or understand how to recover.", "先画状态机，再决定聊天框在其中扮演什么角色。": "Model the state machine first, then decide what role chat should play.",
  "等待完整内容再发布": "Waiting for complete content before publishing", "计划一次性准备所有项目案例、长文和视觉素材。": "Planned to prepare every case study, essay and visual asset before launch.", "网站长期停留在‘快完成了’，也失去了记录过程的价值。": "The site remained ‘almost done’ and lost the value of documenting the process.", "建立 Notes、Experiments 和 Build Log，让不同完成度的内容都有位置。": "Created Notes, Experiments and a Build Log so work at every stage has a place.",
  "这里不保存尴尬，而是保存判断形成的证据。每个被删除的方案，都应该至少留下一条可复用的经验。": "This is not an archive of embarrassment, but evidence of how judgment forms. Every discarded direction should leave at least one reusable lesson.",
  "工作流、工具状态、确认与恢复路径": "Workflows, tool states, confirmation and recovery paths", "从聊天界面扩展为可理解、可控制的任务系统": "Expanded chat into a task system people can understand and control", "Next.js、MDX、静态生成、主题与路由": "Next.js, MDX, static generation, theming and routing", "22+ 静态页面与统一内容管线": "22+ static pages and one content pipeline", "滚动编排、3D 反馈、Canvas 与降级": "Scroll choreography, 3D feedback, Canvas and fallbacks", "桌面增强，触屏与 reduced motion 保持完整": "Enhanced on desktop, complete on touch and reduced motion", "失败分类、运行信号和证据链接": "Failure taxonomy, runtime signals and evidence links", "让判断过程成为可审阅内容": "Made the decision process reviewable",
  "从传统作品集转向持续生长的内容场域。": "Shifted from a traditional portfolio to a continuously growing content field.", "确立 Agent、全栈与交互实验三条内容线。": "Established three lines of work: Agents, full-stack delivery and interaction experiments.", "仍然是一组零散组件和关于个人网站的想法。": "Still a loose set of components and ideas about a personal site.",
  "团队需要一个能从内部知识库回答问题的助手，并且每个结论都必须可追溯。": "The team needed an assistant that could answer from internal knowledge while keeping every conclusion traceable.", "先定义可信答案，而不是先选择向量数据库。": "Define a trustworthy answer before choosing a vector database.", "单次检索能返回相似片段，但复杂问题会混合多个版本的文档，引用也无法稳定对应。": "Single-pass retrieval found similar fragments, but complex questions mixed document versions and produced unstable citations.", "将检索、重排和引用验证拆成独立步骤。": "Separate retrieval, reranking and citation validation.", "工作流改为显式状态图，每一步保存输入、输出与失败原因，并允许从中断点恢复。": "The workflow became an explicit state graph, preserving inputs, outputs and failure reasons at every step with recovery from interruptions.", "用可观察状态换取复杂度，而不是隐藏复杂度。": "Accept complexity in exchange for observable state instead of hiding it.", "界面开始展示检索来源、工具状态与需要用户确认的节点，不再只有一个等待中的聊天气泡。": "The interface began showing sources, tool states and confirmation points instead of one waiting chat bubble.", "把控制权和系统状态同时交还给用户。": "Return both control and system state to the user.", "最终留下的不是某个提示词，而是一套可追踪、可评估、可恢复的 Agent 产品结构。": "What survived was not a prompt, but a traceable, evaluable and recoverable Agent product structure.", "如果重做，会更早建立离线评估集与失败分类。": "If rebuilding, create the offline evaluation set and failure taxonomy earlier.", "项目时间线": "Project timeline", "上一步": "Previous step", "下一步": "Next step",
  "沿时间线查看一个 Agent 项目的失败、架构变化与关键取舍。": "Follow the failures, architecture changes and key trade-offs of an Agent project over time.", "拖动时间不是为了看一个完美结局，而是回到每个信息并不完整、仍需要作出选择的时刻。": "Move through time not to find a perfect ending, but to revisit moments where information was incomplete and a choice still had to be made.",
  "查看一个项目": "View a project", "阅读一个失败案例": "Read a failure case", "进入开放实验室": "Enter the open lab", "播放一首 Field Radio 曲目": "Play a Field Radio track", "留下一个访客信号": "Leave a visitor signal", "找到隐藏层": "Find the hidden layer", "任务会在浏览过程中自动完成，进度只保存在当前浏览器。": "Missions complete as you explore. Progress stays in this browser.", "生成 Field Pass": "Generate Field Pass",
  "在产生外部副作用之前": "Before causing external side effects", "系统不确定用户真实意图时": "When the system is unsure of the user's intent", "成本或等待时间显著增加时": "When cost or wait time rises significantly", "只有不可逆操作才需要": "Only for irreversible actions", "Agent 应该在什么时候主动请求用户确认？": "When should an Agent proactively ask for confirmation?", "基础分布用于呈现讨论样貌；你的选择只保存在本机，不会被计入公共服务器或绑定身份。": "The baseline distribution illustrates the discussion; your choice stays local and is never sent to a public server or tied to your identity.", "下一期问题：当 Agent 失败时，应该展示多少内部过程？": "Next question: how much internal process should an Agent reveal when it fails?", "下载 PNG": "Download PNG", "切换窗口大小": "Toggle window size", "重置桌面": "Reset desktop",
  "拖动窗口标题栏、改变窗口大小并重新排列工作区。布局会保存在当前浏览器。": "Drag window title bars, resize them and rearrange the workspace. The layout is saved in this browser.",
  "把内容、声音、导航和探索方式连接成一个系统。": "Connect content, sound, navigation and exploration into one system.", "验证本地优先的数据痕迹在隐私和参与感之间的平衡。": "Test how local-first traces balance privacy with participation.", "数字分身接口已保留，等待内容与模型配置成熟后接入。": "The digital-twin interface is reserved until the content and model setup are ready.", "11 个内容系统进入同一套导航与视觉语言。": "Eleven content systems now share one navigation and visual language.",
  "不是假装实时的仪表盘，而是一张明确说明当前构建、测试与下一步计划的工作台。": "Not a dashboard pretending to be live, but a workspace that clearly shows what is being built, tested and planned next.",
  "这是最近一次生产构建的公开快照，不伪装成实时监控。每次架构或内容显著变化后更新。": "A public snapshot of the latest production build, without pretending to be live monitoring. It updates after significant architecture or content changes.", "预算目标：交互只增强理解；核心内容在 JavaScript、WebGL 或动画不可用时仍然可以访问。": "Budget principle: interaction should deepen understanding; core content remains accessible without JavaScript, WebGL or animation.",
  "不是展品，": "Not exhibits,", "是可以触碰的想法。": "but ideas you can touch.", "这里收纳尚未成为完整产品的交互研究。移动指针、拖动参数或点击画面，每个实验都会作出回应。": "A collection of interaction studies that have not yet become full products. Move the pointer, adjust a parameter or click the canvas and each experiment responds.", "每个实验只验证一个问题，不急着扩展成完整产品。": "Each experiment tests one question without rushing to become a full product.", "优先使用 Canvas、Web Audio 与 CSS，让想法保持轻盈。": "Prefer Canvas, Web Audio and CSS to keep ideas lightweight.", "实验会被更新、拆解，也可能成为未来项目的一部分。": "Experiments may be updated, dismantled or become part of a future project.",
  "这里暂时不放项目、不解释能力，也不要求你继续点击。隐藏层存在，是为了提醒：不是网站里的每一块空间都必须完成转化。": "There are no projects or capability claims here, and no demand for another click. This hidden layer is a reminder that not every part of a website must convert.",
  "这一页，暂时不在纸上。": "This page is not on paper yet.", "链接可能已经移动，或者它还只是一个没有写下来的念头。": "The link may have moved, or perhaps it is still an unwritten thought.",
  "还没有文章。把": "No writing yet. Put", "就会出现在这里。": "and it will appear here.", "这是一篇格式示例，不是你写的真实文章。替换": "This is a formatting sample, not your final article. Replace", "的内容，或者直接删掉这个文件。": "or delete the file entirely.",
  "主导航": "Main navigation", "进入工作室并掉落工牌": "Enter the studio and drop a badge", "切换到浅色模式": "Switch to light mode", "切换到深色模式": "Switch to dark mode", "Field Radio 音乐播放器": "Field Radio music player", "收起播放器": "Collapse player", "还没有曲目：把音频文件放进 public/audio/，再在 lib/radio-data.ts 里登记一条。": "No tracks yet: put an audio file in public/audio/, then add one entry in lib/radio-data.ts.", "这首放不出来：文件不存在，或是加密/非标准格式（如网易云 ncm），浏览器无法解码。": "This track will not play: the file is missing, or it is an encrypted / non-standard format (such as a NetEase Cloud ncm file) the browser cannot decode.", "去平台收听": "Listen on the platform", "这首只在平台上播放，本站不存音频文件。": "This one plays on the source platform; no audio file is stored here.", "这条还没有可播放的音频，也没有收听链接。": "This entry has neither a playable file nor a listening link yet.", "播放": "Play", "暂停": "Pause", "下一首": "Next track", "音量": "Volume", "播放进度": "Playback position",
  "全部曲目": "All tracks", "悬浮歌词": "Floating lyrics", "歌词": "Lyrics", "收起歌词": "Collapse lyrics", "停靠回播放器上方": "Dock above the player", "正在读取歌词…": "Loading lyrics…", "这首没有歌词。把同名的 .lrc 放进 public/lyrics/ 就会出现。": "No lyrics for this track. Drop a matching .lrc file into public/lyrics/ and it will show up.", "这个 .lrc 里没有可显示的行。": "This .lrc file has no displayable lines.",
  "电台": "Radio", "少数几首确定的曲目，点开就播；播放器常驻右下角。": "A short list of deliberate tracks. Click one to play; the player stays docked bottom-right.", "声音不解释自己。": "Sound does not explain itself.", "点任意一首就开始播，播放器固定在右下角，换页面也不会停。没有本地文件的曲目会带一个跳转按钮，播放在平台那边完成。": "Click any track to start it. The player stays fixed bottom-right and keeps going across pages. Tracks without a local file get a link button and play on the source platform.",
  "立即执行删除": "Delete immediately", "停止并请求确认": "Stop and request confirmation", "静默撤销所有工具": "Silently undo every tool", "用户要求删除数据，但 Agent 已经调用了三个外部工具。你会怎么做？": "The user asks to delete data, but the Agent has already called three external tools. What do you do?", "看似迅速，但工具已经产生外部副作用，删除边界并不明确。": "It looks fast, but the tools have already caused external side effects and the deletion boundary is unclear.", "缺少确认范围和补偿动作，可能造成不可逆的数据损失。": "Without confirming scope or defining compensating actions, this may cause irreversible data loss.", "解释已经发生的调用，列出将被删除的对象，并让用户明确确认。": "Explain what has already run, list the objects to be deleted and ask for explicit confirmation.", "推荐：把高影响动作变成清晰的控制点，同时保留恢复信息。": "Recommended: turn high-impact actions into clear control points while preserving recovery information.", "用户暂时看不到冲突，但部分外部系统可能没有真正的撤销能力。": "The conflict is hidden for now, but some external systems may not offer a true undo.", "只有在每个工具都有经过验证的补偿操作时才成立。": "This works only when every tool has a verified compensating action.", "重新选择": "Choose again",
  "流式回答、来源、确认按钮、错误和恢复入口。": "Streaming answers, sources, confirmation controls, errors and recovery paths.", "把等待、工具执行和部分结果编码为可观察状态。": "Encode waiting, tool execution and partial results as observable states.", "规划、检索、工具调用、确认与恢复的显式图。": "An explicit graph for planning, retrieval, tool use, confirmation and recovery.", "用稳定契约隔离搜索、数据库与外部服务。": "Isolate search, databases and external services behind stable contracts.", "召回、重排、版本过滤与引用验证。": "Recall, reranking, version filtering and citation validation.", "记录轨迹、延迟、失败类别与质量评估。": "Record traces, latency, failure categories and quality evaluations.",
  "先确定内容层次与链接语义，没有动画。": "Establish content hierarchy and link semantics first, without animation.", "增加明确但简单的 hover 反馈。": "Add clear but simple hover feedback.", "让角度跟随指针，并复用 tween 避免高频创建。": "Let the angle follow the pointer and reuse tweens instead of creating them repeatedly.", "标题、装饰与高光进入不同 Z 轴层级。": "Place titles, decoration and highlights on separate Z-axis layers.", "触屏和减少动态效果模式保留完整静态体验。": "Preserve a complete static experience on touch devices and in reduced-motion mode.", "选择组件版本": "Select component version",
  "证明与结构": "Proof & structure", "从能力清单到架构剖面，快速判断我如何定义、实现并验证产品。": "From capability lists to architecture cross-sections, see how I define, build and validate products.", "记录与观测": "Record & observe", "保留版本演变、代码决策与构建预算，让过程可以被检查。": "Preserve version history, code decisions and build budgets so the process can be inspected.", "探索与参与": "Explore & participate", "通过任务和本地优先的协作问题，让浏览成为一次主动探索。": "Turn browsing into active exploration through missions and local-first collaborative questions.", "空间与工具": "Space & tools", "把内容重组为可拖动桌面和可下载卡片，测试新的内容容器。": "Reframe content as a draggable desktop and downloadable cards to test new containers.", "证据模块分组": "Evidence module groups",
  "开放实验室": "Open Lab", "触碰文字、空间、声音与界面反馈的开放实验。": "Open experiments in type, space, sound and interface feedback.", "查看网站每一版的设计与实现变化。": "Review the design and implementation changes across every version of the site.", "了解技术栈、设计原则与构建方式。": "Explore the stack, design principles and build approach.", "此刻正在构建、测试和计划的内容。": "See what is being built, tested and planned right now.", "被放弃的方案，以及它们留下的判断。": "Discarded directions and the judgment they left behind.", "浏览可操作、可下载、可验证的证据层。": "Browse an evidence layer you can operate, download and verify.", "全站探索菜单": "Site-wide explore menu", "从任何页面进入正在发生的工作与证据。": "Enter ongoing work and evidence from any page.",
  "随笔": "Essays", "关于界面、系统与构建过程的短观察。": "Short observations on interfaces, systems and the building process.", "建站不是一次发布，": "A site is not one launch,", "而是一串决定。": "but a series of decisions.", "这里不只记录“新增了什么”，也说明为什么这样设计、哪些方案被放弃，以及下一版准备解决什么。": "This log records more than what changed: it explains why, what was discarded and what the next version should solve.", "从名字、内容结构到动态效果和交付方式，逐篇拆开 NEXTFIELD 背后的设计原则与工程系统。主视觉保留英文，正文随界面语言切换。": "From the name and content structure to motion and delivery, these notes unpack the design principles and engineering system behind NEXTFIELD. The hero stays in English while the body follows the interface language.", "随手写下，": "Written in passing,", "暂不定论。": "left unresolved.", "比技术文章更轻，比动态更新更慢。这里保存关于产品、界面与构建过程的短观察。": "Lighter than technical articles and slower than status updates, these are short observations about products, interfaces and the building process.",
  "序幕": "Prelude", "简介": "Profile", "近况": "Now", "向下切换": "Next section", "查看技术栈": "View the stack", "点击展开": "Click to expand", "再次点击收起": "Click again to collapse", "从 Agent 工作流，到生产级 Web 产品。": "From Agent workflows to production-ready web products.", "Agent 开发 & 全栈开发者 / 专注把 AI 能力变成真正好用的产品。": "Agent and full-stack developer focused on turning AI capabilities into products people can actually use.", "让 AI 能力，成为产品体验。": "Turn AI capability into product experience.", "我把大语言模型、检索系统和工具调用融入真实业务，并完成从产品界面、服务端逻辑到数据层与部署的全栈交付。": "I bring LLMs, retrieval systems and tool use into real businesses, delivering the full stack from product interface and server logic to data and deployment.", "工作流 · RAG · 工具调用": "Workflows · RAG · Tool use", "产品界面 · 服务端 · 部署": "Product UI · Server · Deployment",
  "现在在做这些。": "What I am working on now.", "主要在把 Agent 从能做出来推进到能长期跑：检索质量、失败恢复和成本控制是眼下最花时间的三件事。同时把手上的工程经验整理成可复用的文字。": "I am moving Agents from working once to running reliably over time. Retrieval quality, failure recovery and cost control take most of the attention, while practical engineering lessons become reusable writing.", "最后更新 · 2026 · 09": "Last updated · 2026 · 09", "正在做": "Building", "正在深入": "Exploring", "愿意交流": "Open to discussing", "团队知识库 Agent 的召回优化": "Recall improvements for a team knowledge Agent", "内部 Agent 运行观测平台": "An internal Agent observability platform", "多 Agent 编排的失败恢复": "Failure recovery in multi-Agent orchestration", "长上下文下的成本控制": "Cost control with long context", "Agent 产品落地": "Shipping Agent products", "全栈架构评审": "Full-stack architecture reviews", "技术分享与内训": "Technical talks and internal training",
  "界面层": "Interface layer", "界面与交互": "Interface and interaction", "服务端层": "Server layer", "逻辑与接口": "Logic and APIs", "数据层": "Data layer", "模型与访问": "Models and access", "交付层": "Delivery layer", "构建与运行环境": "Build and runtime", "构建快速、可访问的现代 Web 界面。": "Build fast, accessible modern web interfaces.", "用一致的设计令牌快速落地界面。": "Deliver interfaces quickly with consistent design tokens.", "实现稳定的服务端逻辑与工具链。": "Build stable server logic and tooling.", "设计清楚、可演进的应用接口。": "Design clear and evolvable application APIs.", "实现安全、顺畅的身份验证流程。": "Build secure and seamless authentication flows.", "设计可靠的数据模型、查询与迁移。": "Design reliable data models, queries and migrations.", "保持类型安全的数据访问层。": "Maintain a type-safe data access layer.", "交付可扩展、可复现的生产环境。": "Deliver scalable and reproducible production environments.", "把运行环境固化，本地与线上保持一致。": "Keep local and production environments consistent.", "语言基础": "Language foundation", "用清晰的类型边界保障长期维护。": "Support long-term maintenance with clear type boundaries.", "贯穿全部层级": "Across every layer", "从界面到数据层，构建可持续演进的 Web 产品。": "Build web products that can evolve from interface to data layer.",
  "通过交互课程学习 Agent、全栈与产品实践。": "Learn Agent development, full-stack systems and product practice through interactive lessons.", "不是术语目录，也不是视频播放列表。沿着概念、心智模型、代码骨架和交互检查点，把 Agent 与全栈能力连接成真正的产品。": "Not a glossary or a video playlist. Follow concepts, mental models, code skeletons and interactive checkpoints to connect Agent and full-stack skills into real products.",
  "画廊": "Gallery", "以图片为主的视觉档案：插画、配色与现场记录。": "An image-first visual archive: illustrations, colour studies and field records.", "先有画面，": "Images first,", "再谈解释。": "explanation later.", "这里只有图片和它的一句注脚。每张图下面写清它是什么、为什么留下来，不写更多。": "Images and a single caption each. The line underneath says what it is and why it stayed, and nothing more.", "回到开放实验室": "Back to the open lab", "晶体之眼": "Crystal Iris", "810 × 810 方形插画，先用它把方形裁切与悬停反光两条效果跑通。": "A 810 × 810 square illustration, used first to prove the square crop and hover glare both work."
};

export function translateText(source: string) {
  const direct = EN_TRANSLATIONS[source];
  if (direct) return direct;
  if (/^\d+\s*分钟$/.test(source)) return source.replace("分钟", "min");
  if (/^共\s*\d+\s*篇$/.test(source)) return source.replace("共", "").replace("篇", "notes").trim();
  if (/^\d+\s*个入口$/.test(source)) return source.replace("个入口", "entries");
  return source;
}

const ZH_OVERRIDES: Record<string, string> = {
  "about": "关于我", "projects": "项目", "writing": "写作", "lab": "实验室", "index": "首页", "log": "建站纪事",
  "EXPLORE": "探索", "ENTER STUDIO": "进入工作室", "Field map": "场域地图", "Language preference": "语言偏好",
  "Profile / Overview": "简介 / 概览", "About / Detail": "关于 / 详情",
  "01 / Specialty": "01 / 专长", "02 / Specialty": "02 / 专长", "04 / Now": "04 / 近况", "Contact": "联系",
  "FOCUS": "方向", "STATUS": "状态", "BASED": "所在地", "Agent products": "Agent 产品", "Open to ideas": "开放合作",
  "WORK": "项目", "THINK": "思考", "PLAY": "实验", "NOW": "近况", "View project": "查看项目", "View note": "查看笔记",
  "SELECTED WORK": "精选项目", "SELECTED NOTES": "精选笔记",
  "OPEN EXPERIMENTS": "开放实验", "CAPABILITY MAP": "能力地图", "LIVE STUDIO": "实时工作室", "FIELD RADIO": "场域电台",
  "NOT MORE CLAIMS.": "不再堆叠声明。", "MORE PROOF.": "让证据说话。", "Modules": "模块", "One evidence layer": "同一个证据层",
  "Proof & structure": "证明与结构", "Record & observe": "记录与观测", "Explore & participate": "探索与参与", "Space & tools": "空间与工具",
  "Proof mode / no decoration": "证明模式 / 无装饰", "Capability": "能力", "Scope": "范围", "Evidence": "证据", "Outcome": "结果", "DELIVERY": "交付", "LOCATION": "所在地",
  "Agent products / AI applications": "Agent 产品 / AI 应用", "Product thinking to production UI": "从产品思考到生产界面", "NanChang / remote": "南昌 / 远程",
  "THINGS THAT": "这些尝试", "DIDN'T WORK.": "没有奏效。", "What I tried": "尝试过什么", "Why it failed": "为何失败", "What survived": "留下了什么",
  "THE FIELD,": "这个场域，", "AS A DESKTOP.": "成为桌面。", "THE EXPERIENCE": "体验也", "HAS A BUDGET.": "需要预算。",
  "WHAT'S HAPPENING": "此刻正在", "RIGHT NOW.": "发生什么。", "A PROJECT IS": "项目就是", "A SERIES OF DECISIONS.": "一连串决定。",
  "DESIGN FOR": "设计应服务于", "MORE THAN ONE BODY.": "不同的身体。", "YOU FOUND": "你找到了", "THE QUIET PART.": "安静的一层。",
  "INTERACTIVE CASE STUDY": "交互案例", "Replay the decisions.": "回放这些决定。", "Decision": "决定",
  "Current cycle": "当前周期", "Latest change": "最近更新", "explored": "已探索",
  "Token mode": "令牌模式", "High contrast": "高对比度", "Start": "开始", "Inspect": "检查", "Confirm": "确认",
  "Contrast": "对比度", "Keyboard": "键盘", "Motion": "动态效果", "Fallback": "降级方案",
  "Switching NEXTFIELD to English…": "正在将 NEXTFIELD 切换为英文…", "Continue to the homepage": "继续前往首页", "Build log / 05": "建站纪事 / 05", "Design & system notes": "设计与系统说明", "Essays / Field notes": "随笔 / 场域笔记", "Writing / Index": "写作 / 索引", "Projects / Selected work": "项目 / 精选作品", "LEARN": "学习", "Learn": "学习", "LEARN BY": "通过实践", "BUILDING SYSTEMS.": "学习系统构建。", "3 paths": "3 条路径", "12 lessons": "12 节课程", "Local progress": "本地进度", "进入 FIELD SCHOOL": "进入 FIELD SCHOOL"
};

const REVERSED_TRANSLATIONS: Record<string, string> = Object.fromEntries(
  Object.entries(EN_TRANSLATIONS).map(([zh, en]) => [en, zh]),
);

export function localizeText(source: string, locale: "zh" | "en") {
  if (locale === "en") return translateText(source);
  const direct = ZH_OVERRIDES[source] ?? REVERSED_TRANSLATIONS[source];
  if (direct) return direct;
  if (/^\d+\s*ENTRIES$/i.test(source)) return source.replace(/ENTRIES/i, "个入口");
  return source;
}
