"use client";

import { useEffect, useState } from "react";
import { Activity, CircleDot, Clock3, GitCommitHorizontal } from "lucide-react";
import { TransitionLink } from "@/components/site/transition-link";
import { STUDIO_LOG } from "@/lib/nextfield-data";

export function StudioConsole() {
  const [time, setTime] = useState("--:--:--");
  useEffect(() => { const update = () => setTime(new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Hong_Kong", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date())); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, []);
  return <div className="mt-14 grid gap-4 lg:grid-cols-12"><section className="rounded-[1.75rem] border border-line bg-ink p-6 text-paper lg:col-span-8"><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-mono text-[10px] tracking-[0.16em] text-liquid-foam"><Activity className="size-3.5" /> SYSTEM ACTIVITY</span><span className="font-mono text-[10px] text-paper/40">HKG {time}</span></div><div className="mt-10 space-y-3">{STUDIO_LOG.map((item) => <article className="grid gap-3 rounded-2xl border border-paper/10 bg-paper/5 p-5 sm:grid-cols-[6rem_1fr]" key={item.title}><span className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-liquid-foam"><CircleDot className={`size-3 ${item.status === "active" ? "animate-pulse" : ""}`} />{item.label}</span><div><h2 className="font-display text-2xl">{item.title}</h2><p className="mt-2 text-sm leading-6 text-paper/55">{item.detail}</p></div></article>)}</div></section><aside className="grid gap-4 lg:col-span-4"><div className="rounded-[1.75rem] border border-line bg-panel p-6"><Clock3 className="size-5 text-accent" /><p className="mt-12 font-mono text-[9px] uppercase tracking-[0.16em] text-muted">Current cycle</p><p className="mt-2 font-display text-3xl">October / 08</p><p className="mt-5 text-sm leading-6 text-muted">V2.0.0：问答、内容发现、顶栏与十月双语内容同步更新。</p></div><div className="rounded-[1.75rem] border border-line bg-panel p-6"><GitCommitHorizontal className="size-5 text-accent" /><p className="mt-12 font-mono text-[9px] uppercase tracking-[0.16em] text-muted">Latest change</p><p className="mt-2 font-display text-3xl">Field Agent</p><p className="mt-3 text-sm leading-6 text-muted">局部互动光柱、内容信号与问题种子，连接真实流式站内问答。</p><div className="mt-5 flex flex-col gap-3 text-xs text-accent"><TransitionLink href="/build-log/field-agent-from-chat-to-site-guide">阅读开发纪事 ↗</TransitionLink><TransitionLink href="/colophon/field-agent-sources-streaming-and-limits">查看制作说明 ↗</TransitionLink></div></div></aside></div>;
}
