"use client";

import { useEffect, useState } from "react";
import { Activity, CircleDot, Clock3, GitCommitHorizontal } from "lucide-react";
import { STUDIO_LOG } from "@/lib/nextfield-data";

export function StudioConsole() {
  const [time, setTime] = useState("--:--:--");
  useEffect(() => { const update = () => setTime(new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Hong_Kong", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date())); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, []);
  return <div className="mt-14 grid gap-4 lg:grid-cols-12"><section className="rounded-[1.75rem] border border-line bg-ink p-6 text-paper lg:col-span-8"><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-mono text-[10px] tracking-[0.16em] text-liquid-foam"><Activity className="size-3.5" /> SYSTEM ACTIVITY</span><span className="font-mono text-[10px] text-paper/40">HKG {time}</span></div><div className="mt-10 space-y-3">{STUDIO_LOG.map((item) => <article className="grid gap-3 rounded-2xl border border-paper/10 bg-paper/5 p-5 sm:grid-cols-[6rem_1fr]" key={item.title}><span className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-liquid-foam"><CircleDot className={`size-3 ${item.status === "active" ? "animate-pulse" : ""}`} />{item.label}</span><div><h2 className="font-display text-2xl">{item.title}</h2><p className="mt-2 text-sm leading-6 text-paper/55">{item.detail}</p></div></article>)}</div></section><aside className="grid gap-4 lg:col-span-4"><div className="rounded-[1.75rem] border border-line bg-panel p-6"><Clock3 className="size-5 text-accent" /><p className="mt-12 font-mono text-[9px] uppercase tracking-[0.16em] text-muted">Current cycle</p><p className="mt-2 font-display text-3xl">September / 04</p><div className="mt-5 h-1 overflow-hidden rounded-full bg-line"><span className="block h-full w-[72%] bg-accent" /></div><p className="mt-3 text-xs text-muted">72% explored</p></div><div className="rounded-[1.75rem] border border-line bg-panel p-6"><GitCommitHorizontal className="size-5 text-accent" /><p className="mt-12 font-mono text-[9px] uppercase tracking-[0.16em] text-muted">Latest change</p><p className="mt-2 font-display text-3xl">NEXTFIELD OS</p><p className="mt-3 text-sm leading-6 text-muted">11 个内容系统进入同一套导航与视觉语言。</p></div></aside></div>;
}
